// Package xealth_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package xealth_client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHsReadOrderDeploymentOrderId request
	GetHsReadOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *GetHsReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHsWriteOrderDeploymentWithBody request with any body
	PostHsWriteOrderDeploymentWithBody(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHsWriteOrderDeployment(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, body PostHsWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHsReadOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *GetHsReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHsReadOrderDeploymentOrderIdRequest(c.Server, deployment, orderId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHsWriteOrderDeploymentWithBody(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHsWriteOrderDeploymentRequestWithBody(c.Server, deployment, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHsWriteOrderDeployment(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, body PostHsWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHsWriteOrderDeploymentRequest(c.Server, deployment, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHsReadOrderDeploymentOrderIdRequest generates requests for GetHsReadOrderDeploymentOrderId
func NewGetHsReadOrderDeploymentOrderIdRequest(server string, deployment string, orderId string, params *GetHsReadOrderDeploymentOrderIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "deployment", runtime.ParamLocationPath, deployment)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "orderId", runtime.ParamLocationPath, orderId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hs/read/order/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostHsWriteOrderDeploymentRequest calls the generic PostHsWriteOrderDeployment builder with application/json body
func NewPostHsWriteOrderDeploymentRequest(server string, deployment string, params *PostHsWriteOrderDeploymentParams, body PostHsWriteOrderDeploymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHsWriteOrderDeploymentRequestWithBody(server, deployment, params, "application/json", bodyReader)
}

// NewPostHsWriteOrderDeploymentRequestWithBody generates requests for PostHsWriteOrderDeployment with any type of body
func NewPostHsWriteOrderDeploymentRequestWithBody(server string, deployment string, params *PostHsWriteOrderDeploymentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "deployment", runtime.ParamLocationPath, deployment)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hs/write/order/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Authorization", runtime.ParamLocationHeader, params.Authorization)
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHsReadOrderDeploymentOrderIdWithResponse request
	GetHsReadOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *GetHsReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*GetHsReadOrderDeploymentOrderIdResponse, error)

	// PostHsWriteOrderDeploymentWithBodyWithResponse request with any body
	PostHsWriteOrderDeploymentWithBodyWithResponse(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHsWriteOrderDeploymentResponse, error)

	PostHsWriteOrderDeploymentWithResponse(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, body PostHsWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHsWriteOrderDeploymentResponse, error)
}

type GetHsReadOrderDeploymentOrderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReadOrderResponse
	JSON400      *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetHsReadOrderDeploymentOrderIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHsReadOrderDeploymentOrderIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHsWriteOrderDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateOrderResponse
	JSON400      *struct {
		Error string `json:"error"`
	}
	JSON404 *struct {
		Error string `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r PostHsWriteOrderDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHsWriteOrderDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHsReadOrderDeploymentOrderIdWithResponse request returning *GetHsReadOrderDeploymentOrderIdResponse
func (c *ClientWithResponses) GetHsReadOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *GetHsReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*GetHsReadOrderDeploymentOrderIdResponse, error) {
	rsp, err := c.GetHsReadOrderDeploymentOrderId(ctx, deployment, orderId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHsReadOrderDeploymentOrderIdResponse(rsp)
}

// PostHsWriteOrderDeploymentWithBodyWithResponse request with arbitrary body returning *PostHsWriteOrderDeploymentResponse
func (c *ClientWithResponses) PostHsWriteOrderDeploymentWithBodyWithResponse(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHsWriteOrderDeploymentResponse, error) {
	rsp, err := c.PostHsWriteOrderDeploymentWithBody(ctx, deployment, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHsWriteOrderDeploymentResponse(rsp)
}

func (c *ClientWithResponses) PostHsWriteOrderDeploymentWithResponse(ctx context.Context, deployment string, params *PostHsWriteOrderDeploymentParams, body PostHsWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHsWriteOrderDeploymentResponse, error) {
	rsp, err := c.PostHsWriteOrderDeployment(ctx, deployment, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHsWriteOrderDeploymentResponse(rsp)
}

// ParseGetHsReadOrderDeploymentOrderIdResponse parses an HTTP response from a GetHsReadOrderDeploymentOrderIdWithResponse call
func ParseGetHsReadOrderDeploymentOrderIdResponse(rsp *http.Response) (*GetHsReadOrderDeploymentOrderIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHsReadOrderDeploymentOrderIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReadOrderResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePostHsWriteOrderDeploymentResponse parses an HTTP response from a PostHsWriteOrderDeploymentWithResponse call
func ParsePostHsWriteOrderDeploymentResponse(rsp *http.Response) (*PostHsWriteOrderDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHsWriteOrderDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateOrderResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
