// Package xealth_client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package xealth_client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId Batch File Schema
	//
	// <img src="xealth_api_2.0_batch_file_schema.svg"/>
	//
	// Certain orders can be generated via a batch file provided by the health system. For orders of this type, Xealth provides a **batchFileSchemaId** along with the rest of the details of the order. Subscribers can then call into the Data Retrieval endpoint with this batchFileSchemaId in order determine the JSON schema of the batch file data provided within the order details.
	//
	// Corresponds with GET /partner/read/batch_file_schema/{deployment}/{batchFileSchemaId} (the `GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId` operationId).
	GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId(ctx context.Context, deployment string, batchFileSchemaId string, params *GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPartnerReadOrderDeploymentOrderId Retrieve Order
	//
	// <img src="xealth_api_2.0_order_retrieve.svg"/>
	//
	// Orders related to digital content can be prescribed from a variety of sources within Health Systems. Xealth will notify subscribers of these order events using a unified notification message regardless of the origination of the order.
	// <br><br>
	// Once notified about an event related to an order, Subscribers can call into Xealth to fetch more information about that order. Partner Subscribers can make use of these order details to complete the patient enrollment process and/or validate the uniqueness of the patient within their system.
	//
	// Corresponds with GET /partner/read/order/{deployment}/{orderId} (the `GetPartnerReadOrderDeploymentOrderId` operationId).
	GetPartnerReadOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *GetPartnerReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPartnerWriteOrderDeploymentWithBody Create Order
	//
	// <img src="xealth_api_2.0_order_create_partner.svg"/>
	//
	// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
	// <br><br>
	// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
	// <br><br>
	// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
	PostPartnerWriteOrderDeploymentWithBody(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPartnerWriteOrderDeployment Create Order
	//
	// <img src="xealth_api_2.0_order_create_partner.svg"/>
	//
	// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
	// <br><br>
	// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
	// <br><br>
	// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
	PostPartnerWriteOrderDeployment(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, body PostPartnerWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePartnerWriteOrderDeploymentOrderId Cancel Order
	//
	// <img src="xealth_api_2.0_order_cancel.svg"/>
	//
	// Partner Subscribers can submit to the Cancel Order endpoint to unenroll a patient from their program(s). This cancellation event will update the status of an existing order for that patient within Xealth. An event notification will then be generated for the cancellation with the <code>eventType</code> valued to <code>order</code> and the <code>eventContext</code> valued to <code>cancel</code>.
	// <br><br>
	// The reason for a Partner Subscriber to unenroll a patient within Xealth is to sever the relationship between their program and the patient at the specified Health System. Within the Xealth Provider API, the contract between a Partner Subscriber's program and the Health System for a given patient is dictated by the Xealth order. So long as that order is active, the contract exists. By canceling an order, the Partner Subscriber is indicating that they no longer wish to actively maintain their relationship for this patient and the previously ordered program.
	// <br><br>
	// As mentioned, unenrolling a patient with Xealth cancels an existing order within the Xealth system. This, in turn, stops the patient from being accessed within Monitor View (via the Get Programs endpoint).  Likewise, canceling an order prevents the Subscriber from both sending messages to the patient's care team (via the Provider Message endpoint) as well as updates to that order (via the Order Update endpoint).
	//
	// Corresponds with DELETE /partner/write/order/{deployment}/{orderId} (the `DeletePartnerWriteOrderDeploymentOrderId` operationId).
	DeletePartnerWriteOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *DeletePartnerWriteOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutPartnerWriteOrderDeploymentOrderIdWithBody Update Order
	//
	// <img src="xealth_api_2.0_order_update.svg"/>
	//
	// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
	PutPartnerWriteOrderDeploymentOrderIdWithBody(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutPartnerWriteOrderDeploymentOrderId Update Order
	//
	// <img src="xealth_api_2.0_order_update.svg"/>
	//
	// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
	PutPartnerWriteOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, body PutPartnerWriteOrderDeploymentOrderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId Batch File Schema
//
// <img src="xealth_api_2.0_batch_file_schema.svg"/>
//
// Certain orders can be generated via a batch file provided by the health system. For orders of this type, Xealth provides a **batchFileSchemaId** along with the rest of the details of the order. Subscribers can then call into the Data Retrieval endpoint with this batchFileSchemaId in order determine the JSON schema of the batch file data provided within the order details.
//
// Corresponds with GET /partner/read/batch_file_schema/{deployment}/{batchFileSchemaId} (the `GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId` operationId).
func (c *Client) GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId(ctx context.Context, deployment string, batchFileSchemaId string, params *GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdRequest(c.Server, deployment, batchFileSchemaId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPartnerReadOrderDeploymentOrderId Retrieve Order
//
// <img src="xealth_api_2.0_order_retrieve.svg"/>
//
// Orders related to digital content can be prescribed from a variety of sources within Health Systems. Xealth will notify subscribers of these order events using a unified notification message regardless of the origination of the order.
// <br><br>
// Once notified about an event related to an order, Subscribers can call into Xealth to fetch more information about that order. Partner Subscribers can make use of these order details to complete the patient enrollment process and/or validate the uniqueness of the patient within their system.
//
// Corresponds with GET /partner/read/order/{deployment}/{orderId} (the `GetPartnerReadOrderDeploymentOrderId` operationId).
func (c *Client) GetPartnerReadOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *GetPartnerReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPartnerReadOrderDeploymentOrderIdRequest(c.Server, deployment, orderId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostPartnerWriteOrderDeploymentWithBody Create Order
//
// <img src="xealth_api_2.0_order_create_partner.svg"/>
//
// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
// <br><br>
// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
// <br><br>
// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
func (c *Client) PostPartnerWriteOrderDeploymentWithBody(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPartnerWriteOrderDeploymentRequestWithBody(c.Server, deployment, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostPartnerWriteOrderDeployment Create Order
//
// <img src="xealth_api_2.0_order_create_partner.svg"/>
//
// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
// <br><br>
// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
// <br><br>
// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
func (c *Client) PostPartnerWriteOrderDeployment(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, body PostPartnerWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPartnerWriteOrderDeploymentRequest(c.Server, deployment, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeletePartnerWriteOrderDeploymentOrderId Cancel Order
//
// <img src="xealth_api_2.0_order_cancel.svg"/>
//
// Partner Subscribers can submit to the Cancel Order endpoint to unenroll a patient from their program(s). This cancellation event will update the status of an existing order for that patient within Xealth. An event notification will then be generated for the cancellation with the <code>eventType</code> valued to <code>order</code> and the <code>eventContext</code> valued to <code>cancel</code>.
// <br><br>
// The reason for a Partner Subscriber to unenroll a patient within Xealth is to sever the relationship between their program and the patient at the specified Health System. Within the Xealth Provider API, the contract between a Partner Subscriber's program and the Health System for a given patient is dictated by the Xealth order. So long as that order is active, the contract exists. By canceling an order, the Partner Subscriber is indicating that they no longer wish to actively maintain their relationship for this patient and the previously ordered program.
// <br><br>
// As mentioned, unenrolling a patient with Xealth cancels an existing order within the Xealth system. This, in turn, stops the patient from being accessed within Monitor View (via the Get Programs endpoint).  Likewise, canceling an order prevents the Subscriber from both sending messages to the patient's care team (via the Provider Message endpoint) as well as updates to that order (via the Order Update endpoint).
//
// Corresponds with DELETE /partner/write/order/{deployment}/{orderId} (the `DeletePartnerWriteOrderDeploymentOrderId` operationId).
func (c *Client) DeletePartnerWriteOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *DeletePartnerWriteOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePartnerWriteOrderDeploymentOrderIdRequest(c.Server, deployment, orderId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutPartnerWriteOrderDeploymentOrderIdWithBody Update Order
//
// <img src="xealth_api_2.0_order_update.svg"/>
//
// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
func (c *Client) PutPartnerWriteOrderDeploymentOrderIdWithBody(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutPartnerWriteOrderDeploymentOrderIdRequestWithBody(c.Server, deployment, orderId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PutPartnerWriteOrderDeploymentOrderId Update Order
//
// <img src="xealth_api_2.0_order_update.svg"/>
//
// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
func (c *Client) PutPartnerWriteOrderDeploymentOrderId(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, body PutPartnerWriteOrderDeploymentOrderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutPartnerWriteOrderDeploymentOrderIdRequest(c.Server, deployment, orderId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdRequest constructs an http.Request for the GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId method
func NewGetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdRequest(server string, deployment string, batchFileSchemaId string, params *GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment", deployment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "batchFileSchemaId", batchFileSchemaId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/read/batch_file_schema/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewGetPartnerReadOrderDeploymentOrderIdRequest constructs an http.Request for the GetPartnerReadOrderDeploymentOrderId method
func NewGetPartnerReadOrderDeploymentOrderIdRequest(server string, deployment string, orderId string, params *GetPartnerReadOrderDeploymentOrderIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment", deployment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "orderId", orderId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/read/order/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPostPartnerWriteOrderDeploymentRequest calls the generic PostPartnerWriteOrderDeployment builder with application/json body
func NewPostPartnerWriteOrderDeploymentRequest(server string, deployment string, params *PostPartnerWriteOrderDeploymentParams, body PostPartnerWriteOrderDeploymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPartnerWriteOrderDeploymentRequestWithBody(server, deployment, params, "application/json", bodyReader)
}

// NewPostPartnerWriteOrderDeploymentRequestWithBody constructs an http.Request for the PostPartnerWriteOrderDeployment method, with any body, and a specified content type
func NewPostPartnerWriteOrderDeploymentRequestWithBody(server string, deployment string, params *PostPartnerWriteOrderDeploymentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment", deployment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/write/order/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewDeletePartnerWriteOrderDeploymentOrderIdRequest constructs an http.Request for the DeletePartnerWriteOrderDeploymentOrderId method
func NewDeletePartnerWriteOrderDeploymentOrderIdRequest(server string, deployment string, orderId string, params *DeletePartnerWriteOrderDeploymentOrderIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment", deployment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "orderId", orderId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/write/order/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

// NewPutPartnerWriteOrderDeploymentOrderIdRequest calls the generic PutPartnerWriteOrderDeploymentOrderId builder with application/json body
func NewPutPartnerWriteOrderDeploymentOrderIdRequest(server string, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, body PutPartnerWriteOrderDeploymentOrderIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutPartnerWriteOrderDeploymentOrderIdRequestWithBody(server, deployment, orderId, params, "application/json", bodyReader)
}

// NewPutPartnerWriteOrderDeploymentOrderIdRequestWithBody constructs an http.Request for the PutPartnerWriteOrderDeploymentOrderId method, with any body, and a specified content type
func NewPutPartnerWriteOrderDeploymentOrderIdRequestWithBody(server string, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "deployment", deployment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "orderId", orderId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/partner/write/order/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdWithResponse Batch File Schema
	//
	// <img src="xealth_api_2.0_batch_file_schema.svg"/>
	//
	// Certain orders can be generated via a batch file provided by the health system. For orders of this type, Xealth provides a **batchFileSchemaId** along with the rest of the details of the order. Subscribers can then call into the Data Retrieval endpoint with this batchFileSchemaId in order determine the JSON schema of the batch file data provided within the order details.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /partner/read/batch_file_schema/{deployment}/{batchFileSchemaId} (the `GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId` operationId).
	GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdWithResponse(ctx context.Context, deployment string, batchFileSchemaId string, params *GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdParams, reqEditors ...RequestEditorFn) (*GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse, error)

	// GetPartnerReadOrderDeploymentOrderIdWithResponse Retrieve Order
	//
	// <img src="xealth_api_2.0_order_retrieve.svg"/>
	//
	// Orders related to digital content can be prescribed from a variety of sources within Health Systems. Xealth will notify subscribers of these order events using a unified notification message regardless of the origination of the order.
	// <br><br>
	// Once notified about an event related to an order, Subscribers can call into Xealth to fetch more information about that order. Partner Subscribers can make use of these order details to complete the patient enrollment process and/or validate the uniqueness of the patient within their system.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /partner/read/order/{deployment}/{orderId} (the `GetPartnerReadOrderDeploymentOrderId` operationId).
	GetPartnerReadOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *GetPartnerReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*GetPartnerReadOrderDeploymentOrderIdResponse, error)

	// PostPartnerWriteOrderDeploymentWithBodyWithResponse Create Order
	//
	// <img src="xealth_api_2.0_order_create_partner.svg"/>
	//
	// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
	// <br><br>
	// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
	// <br><br>
	// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
	PostPartnerWriteOrderDeploymentWithBodyWithResponse(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPartnerWriteOrderDeploymentResponse, error)

	// PostPartnerWriteOrderDeploymentWithResponse Create Order
	//
	// <img src="xealth_api_2.0_order_create_partner.svg"/>
	//
	// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
	// <br><br>
	// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
	// <br><br>
	// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
	PostPartnerWriteOrderDeploymentWithResponse(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, body PostPartnerWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPartnerWriteOrderDeploymentResponse, error)

	// DeletePartnerWriteOrderDeploymentOrderIdWithResponse Cancel Order
	//
	// <img src="xealth_api_2.0_order_cancel.svg"/>
	//
	// Partner Subscribers can submit to the Cancel Order endpoint to unenroll a patient from their program(s). This cancellation event will update the status of an existing order for that patient within Xealth. An event notification will then be generated for the cancellation with the <code>eventType</code> valued to <code>order</code> and the <code>eventContext</code> valued to <code>cancel</code>.
	// <br><br>
	// The reason for a Partner Subscriber to unenroll a patient within Xealth is to sever the relationship between their program and the patient at the specified Health System. Within the Xealth Provider API, the contract between a Partner Subscriber's program and the Health System for a given patient is dictated by the Xealth order. So long as that order is active, the contract exists. By canceling an order, the Partner Subscriber is indicating that they no longer wish to actively maintain their relationship for this patient and the previously ordered program.
	// <br><br>
	// As mentioned, unenrolling a patient with Xealth cancels an existing order within the Xealth system. This, in turn, stops the patient from being accessed within Monitor View (via the Get Programs endpoint).  Likewise, canceling an order prevents the Subscriber from both sending messages to the patient's care team (via the Provider Message endpoint) as well as updates to that order (via the Order Update endpoint).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /partner/write/order/{deployment}/{orderId} (the `DeletePartnerWriteOrderDeploymentOrderId` operationId).
	DeletePartnerWriteOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *DeletePartnerWriteOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*DeletePartnerWriteOrderDeploymentOrderIdResponse, error)

	// PutPartnerWriteOrderDeploymentOrderIdWithBodyWithResponse Update Order
	//
	// <img src="xealth_api_2.0_order_update.svg"/>
	//
	// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
	PutPartnerWriteOrderDeploymentOrderIdWithBodyWithResponse(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutPartnerWriteOrderDeploymentOrderIdResponse, error)

	// PutPartnerWriteOrderDeploymentOrderIdWithResponse Update Order
	//
	// <img src="xealth_api_2.0_order_update.svg"/>
	//
	// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
	PutPartnerWriteOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, body PutPartnerWriteOrderDeploymentOrderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutPartnerWriteOrderDeploymentOrderIdResponse, error)
}

type GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// BatchFileSchema JSON schema of the batch file
		BatchFileSchema map[string]interface{} `json:"batchFileSchema"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Error string `json:"error"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse) GetJSON200() *struct {
	// BatchFileSchema JSON schema of the batch file
	BatchFileSchema map[string]interface{} `json:"batchFileSchema"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse) GetJSON400() *struct {
	Error string `json:"error"`
} {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPartnerReadOrderDeploymentOrderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ReadOrderResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Error string `json:"error"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPartnerReadOrderDeploymentOrderIdResponse) GetJSON200() *ReadOrderResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetPartnerReadOrderDeploymentOrderIdResponse) GetJSON400() *struct {
	Error string `json:"error"`
} {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r GetPartnerReadOrderDeploymentOrderIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPartnerReadOrderDeploymentOrderIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPartnerReadOrderDeploymentOrderIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPartnerReadOrderDeploymentOrderIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostPartnerWriteOrderDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Deployment The Xealth-defined ID of the Health System
		Deployment string `json:"deployment"`

		// OrderId Xealth-generated value that uniquely identifies the order
		OrderId string `json:"orderId"`

		// PartnerId Xealth-generated value that uniquely identifies the partner
		PartnerId string `json:"partnerId"`

		// PatientIdentity Object identifying the patient
		PatientIdentity struct {
			// HistoricalIds List of the historical identifiers related to the patient
			HistoricalIds *[]struct {
				// Id Value of the identifier for the patient
				Id string `json:"id"`

				// Origin Defines the originating system from which the id value was sourced
				Origin PostPartnerWriteOrderDeployment200JSONResponseBodyPatientIdentityHistoricalIdsOrigin `json:"origin"`

				// Type Defines the type of identifier associated with the id
				Type string `json:"type"`
			} `json:"historicalIds,omitempty"`

			// Ids List of the current identifiers related to the patient
			Ids []struct {
				// Id Value of the identifier for the patient
				Id string `json:"id"`

				// Origin Defines the originating system from which the id value was sourced
				Origin PostPartnerWriteOrderDeployment200JSONResponseBodyPatientIdentityIdsOrigin `json:"origin"`

				// Type Defines the type of identifier associated with the id
				Type string `json:"type"`
			} `json:"ids"`
		} `json:"patientIdentity"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Error string `json:"error"`
	}
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *struct {
		Error string `json:"error"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostPartnerWriteOrderDeploymentResponse) GetJSON200() *struct {
	// Deployment The Xealth-defined ID of the Health System
	Deployment string `json:"deployment"`

	// OrderId Xealth-generated value that uniquely identifies the order
	OrderId string `json:"orderId"`

	// PartnerId Xealth-generated value that uniquely identifies the partner
	PartnerId string `json:"partnerId"`

	// PatientIdentity Object identifying the patient
	PatientIdentity struct {
		// HistoricalIds List of the historical identifiers related to the patient
		HistoricalIds *[]struct {
			// Id Value of the identifier for the patient
			Id string `json:"id"`

			// Origin Defines the originating system from which the id value was sourced
			Origin PostPartnerWriteOrderDeployment200JSONResponseBodyPatientIdentityHistoricalIdsOrigin `json:"origin"`

			// Type Defines the type of identifier associated with the id
			Type string `json:"type"`
		} `json:"historicalIds,omitempty"`

		// Ids List of the current identifiers related to the patient
		Ids []struct {
			// Id Value of the identifier for the patient
			Id string `json:"id"`

			// Origin Defines the originating system from which the id value was sourced
			Origin PostPartnerWriteOrderDeployment200JSONResponseBodyPatientIdentityIdsOrigin `json:"origin"`

			// Type Defines the type of identifier associated with the id
			Type string `json:"type"`
		} `json:"ids"`
	} `json:"patientIdentity"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostPartnerWriteOrderDeploymentResponse) GetJSON400() *struct {
	Error string `json:"error"`
} {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostPartnerWriteOrderDeploymentResponse) GetJSON404() *struct {
	Error string `json:"error"`
} {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r PostPartnerWriteOrderDeploymentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostPartnerWriteOrderDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPartnerWriteOrderDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostPartnerWriteOrderDeploymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeletePartnerWriteOrderDeploymentOrderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Error string `json:"error"`
	}
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeletePartnerWriteOrderDeploymentOrderIdResponse) GetJSON400() *struct {
	Error string `json:"error"`
} {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r DeletePartnerWriteOrderDeploymentOrderIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeletePartnerWriteOrderDeploymentOrderIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePartnerWriteOrderDeploymentOrderIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeletePartnerWriteOrderDeploymentOrderIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PutPartnerWriteOrderDeploymentOrderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *struct {
		Error string `json:"error"`
	}
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PutPartnerWriteOrderDeploymentOrderIdResponse) GetJSON400() *struct {
	Error string `json:"error"`
} {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r PutPartnerWriteOrderDeploymentOrderIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PutPartnerWriteOrderDeploymentOrderIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutPartnerWriteOrderDeploymentOrderIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PutPartnerWriteOrderDeploymentOrderIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdWithResponse Batch File Schema
//
// <img src="xealth_api_2.0_batch_file_schema.svg"/>
//
// Certain orders can be generated via a batch file provided by the health system. For orders of this type, Xealth provides a **batchFileSchemaId** along with the rest of the details of the order. Subscribers can then call into the Data Retrieval endpoint with this batchFileSchemaId in order determine the JSON schema of the batch file data provided within the order details.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /partner/read/batch_file_schema/{deployment}/{batchFileSchemaId} (the `GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId` operationId).
func (c *ClientWithResponses) GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdWithResponse(ctx context.Context, deployment string, batchFileSchemaId string, params *GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdParams, reqEditors ...RequestEditorFn) (*GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse, error) {
	rsp, err := c.GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaId(ctx, deployment, batchFileSchemaId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse(rsp)
}

// GetPartnerReadOrderDeploymentOrderIdWithResponse Retrieve Order
//
// <img src="xealth_api_2.0_order_retrieve.svg"/>
//
// Orders related to digital content can be prescribed from a variety of sources within Health Systems. Xealth will notify subscribers of these order events using a unified notification message regardless of the origination of the order.
// <br><br>
// Once notified about an event related to an order, Subscribers can call into Xealth to fetch more information about that order. Partner Subscribers can make use of these order details to complete the patient enrollment process and/or validate the uniqueness of the patient within their system.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /partner/read/order/{deployment}/{orderId} (the `GetPartnerReadOrderDeploymentOrderId` operationId).
func (c *ClientWithResponses) GetPartnerReadOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *GetPartnerReadOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*GetPartnerReadOrderDeploymentOrderIdResponse, error) {
	rsp, err := c.GetPartnerReadOrderDeploymentOrderId(ctx, deployment, orderId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPartnerReadOrderDeploymentOrderIdResponse(rsp)
}

// PostPartnerWriteOrderDeploymentWithBodyWithResponse Create Order
//
// <img src="xealth_api_2.0_order_create_partner.svg"/>
//
// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
// <br><br>
// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
// <br><br>
// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
func (c *ClientWithResponses) PostPartnerWriteOrderDeploymentWithBodyWithResponse(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPartnerWriteOrderDeploymentResponse, error) {
	rsp, err := c.PostPartnerWriteOrderDeploymentWithBody(ctx, deployment, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPartnerWriteOrderDeploymentResponse(rsp)
}

// PostPartnerWriteOrderDeploymentWithResponse Create Order
//
// <img src="xealth_api_2.0_order_create_partner.svg"/>
//
// Partner Subscribers can write to the Create Order endpoint to enroll a patient into one or more of their programs. This enrollment event will create a new order for that patient within Xealth. An event notification will then be generated for the order and the <code>orderSource</code> will be valued as <code>subscriberenrollment</code>.
// <br><br>
// The reason for a Partner Subscriber to enroll a patient with Xealth is to account for patients that either have a pre-existing relationship with the Subscriber or else were enrolled with the Subscriber outside of a Xealth-managed order event. In either situation, the Subscriber cannot interact with the Xealth Provider API without first enrolling the patient with Xealth.
// <br><br>
// As mentioned, enrolling a patient with Xealth creates a new order within the Xealth system. This, in turn, allows for the patient to be accessed within Monitor View (via the Get Programs endpoint) and gives care team members access to the Subscriber's dashboard for that patient (via the Get Program Url endpoint). Likewise, having an order allows the Subscriber to send messages to the patient's care team (via the Provider Message endpoint) as well as provide updates to that order (via the Order Update endpoint).
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /partner/write/order/{deployment} (the `PostPartnerWriteOrderDeployment` operationId).
func (c *ClientWithResponses) PostPartnerWriteOrderDeploymentWithResponse(ctx context.Context, deployment string, params *PostPartnerWriteOrderDeploymentParams, body PostPartnerWriteOrderDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPartnerWriteOrderDeploymentResponse, error) {
	rsp, err := c.PostPartnerWriteOrderDeployment(ctx, deployment, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPartnerWriteOrderDeploymentResponse(rsp)
}

// DeletePartnerWriteOrderDeploymentOrderIdWithResponse Cancel Order
//
// <img src="xealth_api_2.0_order_cancel.svg"/>
//
// Partner Subscribers can submit to the Cancel Order endpoint to unenroll a patient from their program(s). This cancellation event will update the status of an existing order for that patient within Xealth. An event notification will then be generated for the cancellation with the <code>eventType</code> valued to <code>order</code> and the <code>eventContext</code> valued to <code>cancel</code>.
// <br><br>
// The reason for a Partner Subscriber to unenroll a patient within Xealth is to sever the relationship between their program and the patient at the specified Health System. Within the Xealth Provider API, the contract between a Partner Subscriber's program and the Health System for a given patient is dictated by the Xealth order. So long as that order is active, the contract exists. By canceling an order, the Partner Subscriber is indicating that they no longer wish to actively maintain their relationship for this patient and the previously ordered program.
// <br><br>
// As mentioned, unenrolling a patient with Xealth cancels an existing order within the Xealth system. This, in turn, stops the patient from being accessed within Monitor View (via the Get Programs endpoint).  Likewise, canceling an order prevents the Subscriber from both sending messages to the patient's care team (via the Provider Message endpoint) as well as updates to that order (via the Order Update endpoint).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /partner/write/order/{deployment}/{orderId} (the `DeletePartnerWriteOrderDeploymentOrderId` operationId).
func (c *ClientWithResponses) DeletePartnerWriteOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *DeletePartnerWriteOrderDeploymentOrderIdParams, reqEditors ...RequestEditorFn) (*DeletePartnerWriteOrderDeploymentOrderIdResponse, error) {
	rsp, err := c.DeletePartnerWriteOrderDeploymentOrderId(ctx, deployment, orderId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePartnerWriteOrderDeploymentOrderIdResponse(rsp)
}

// PutPartnerWriteOrderDeploymentOrderIdWithBodyWithResponse Update Order
//
// <img src="xealth_api_2.0_order_update.svg"/>
//
// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
func (c *ClientWithResponses) PutPartnerWriteOrderDeploymentOrderIdWithBodyWithResponse(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutPartnerWriteOrderDeploymentOrderIdResponse, error) {
	rsp, err := c.PutPartnerWriteOrderDeploymentOrderIdWithBody(ctx, deployment, orderId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutPartnerWriteOrderDeploymentOrderIdResponse(rsp)
}

// PutPartnerWriteOrderDeploymentOrderIdWithResponse Update Order
//
// <img src="xealth_api_2.0_order_update.svg"/>
//
// Subscribers have the option to log additional updates to an order long after the original has been received and processed. These updates can be used to track the current status of the patient within the Subscriber's program(s) as well as record the specific services the patient is receiving. This information can then be used to drive additional workflow actions within Xealth, such as prescribing additional digital content or triggering supplemental patient outreach. Additionally, this data can be reported back to the originating Health System for the purposes validating the efficacy of the program based on patient outcomes.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /partner/write/order/{deployment}/{orderId} (the `PutPartnerWriteOrderDeploymentOrderId` operationId).
func (c *ClientWithResponses) PutPartnerWriteOrderDeploymentOrderIdWithResponse(ctx context.Context, deployment string, orderId string, params *PutPartnerWriteOrderDeploymentOrderIdParams, body PutPartnerWriteOrderDeploymentOrderIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutPartnerWriteOrderDeploymentOrderIdResponse, error) {
	rsp, err := c.PutPartnerWriteOrderDeploymentOrderId(ctx, deployment, orderId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutPartnerWriteOrderDeploymentOrderIdResponse(rsp)
}

// ParseGetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse parses an HTTP response from a GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdWithResponse call
func ParseGetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse(rsp *http.Response) (*GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPartnerReadBatchFileSchemaDeploymentBatchFileSchemaIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// BatchFileSchema JSON schema of the batch file
			BatchFileSchema map[string]interface{} `json:"batchFileSchema"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case rsp.StatusCode == 500:
		break // No content-type

	case rsp.StatusCode == 504:
		break // No content-type

	}

	return response, nil
}

// ParseGetPartnerReadOrderDeploymentOrderIdResponse parses an HTTP response from a GetPartnerReadOrderDeploymentOrderIdWithResponse call
func ParseGetPartnerReadOrderDeploymentOrderIdResponse(rsp *http.Response) (*GetPartnerReadOrderDeploymentOrderIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPartnerReadOrderDeploymentOrderIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReadOrderResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case rsp.StatusCode == 500:
		break // No content-type

	case rsp.StatusCode == 504:
		break // No content-type

	}

	return response, nil
}

// ParsePostPartnerWriteOrderDeploymentResponse parses an HTTP response from a PostPartnerWriteOrderDeploymentWithResponse call
func ParsePostPartnerWriteOrderDeploymentResponse(rsp *http.Response) (*PostPartnerWriteOrderDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPartnerWriteOrderDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Deployment The Xealth-defined ID of the Health System
			Deployment string `json:"deployment"`

			// OrderId Xealth-generated value that uniquely identifies the order
			OrderId string `json:"orderId"`

			// PartnerId Xealth-generated value that uniquely identifies the partner
			PartnerId string `json:"partnerId"`

			// PatientIdentity Object identifying the patient
			PatientIdentity struct {
				// HistoricalIds List of the historical identifiers related to the patient
				HistoricalIds *[]struct {
					// Id Value of the identifier for the patient
					Id string `json:"id"`

					// Origin Defines the originating system from which the id value was sourced
					Origin PostPartnerWriteOrderDeployment200JSONResponseBodyPatientIdentityHistoricalIdsOrigin `json:"origin"`

					// Type Defines the type of identifier associated with the id
					Type string `json:"type"`
				} `json:"historicalIds,omitempty"`

				// Ids List of the current identifiers related to the patient
				Ids []struct {
					// Id Value of the identifier for the patient
					Id string `json:"id"`

					// Origin Defines the originating system from which the id value was sourced
					Origin PostPartnerWriteOrderDeployment200JSONResponseBodyPatientIdentityIdsOrigin `json:"origin"`

					// Type Defines the type of identifier associated with the id
					Type string `json:"type"`
				} `json:"ids"`
			} `json:"patientIdentity"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case rsp.StatusCode == 500:
		break // No content-type

	case rsp.StatusCode == 504:
		break // No content-type

	}

	return response, nil
}

// ParseDeletePartnerWriteOrderDeploymentOrderIdResponse parses an HTTP response from a DeletePartnerWriteOrderDeploymentOrderIdWithResponse call
func ParseDeletePartnerWriteOrderDeploymentOrderIdResponse(rsp *http.Response) (*DeletePartnerWriteOrderDeploymentOrderIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePartnerWriteOrderDeploymentOrderIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case rsp.StatusCode == 500:
		break // No content-type

	case rsp.StatusCode == 504:
		break // No content-type

	}

	return response, nil
}

// ParsePutPartnerWriteOrderDeploymentOrderIdResponse parses an HTTP response from a PutPartnerWriteOrderDeploymentOrderIdWithResponse call
func ParsePutPartnerWriteOrderDeploymentOrderIdResponse(rsp *http.Response) (*PutPartnerWriteOrderDeploymentOrderIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutPartnerWriteOrderDeploymentOrderIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error string `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case rsp.StatusCode == 500:
		break // No content-type

	case rsp.StatusCode == 504:
		break // No content-type

	}

	return response, nil
}

// WebhookInitiator sends OpenAPI 3.1 webhook requests to target URLs.
// Modeled on the generated Client, but with no stored Server -- the full
// target URL is provided per-call by the caller (typically discovered
// from a subscription registration).
type WebhookInitiator struct {
	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// WebhookInitiatorOption allows setting custom parameters during construction.
type WebhookInitiatorOption func(*WebhookInitiator) error

// NewWebhookInitiator creates a new WebhookInitiator with reasonable defaults.
func NewWebhookInitiator(opts ...WebhookInitiatorOption) (*WebhookInitiator, error) {
	initiator := WebhookInitiator{}
	for _, o := range opts {
		if err := o(&initiator); err != nil {
			return nil, err
		}
	}
	if initiator.Client == nil {
		initiator.Client = &http.Client{}
	}
	return &initiator, nil
}

// WithWebhookHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithWebhookHTTPClient(doer HttpRequestDoer) WebhookInitiatorOption {
	return func(p *WebhookInitiator) error {
		p.Client = doer
		return nil
	}
}

// WithWebhookRequestEditorFn allows setting up a callback function, which
// will be called right before sending the webhook request. This can be
// used to mutate the request, e.g. to add signature headers.
func WithWebhookRequestEditorFn(fn RequestEditorFn) WebhookInitiatorOption {
	return func(p *WebhookInitiator) error {
		p.RequestEditors = append(p.RequestEditors, fn)
		return nil
	}
}

func (p *WebhookInitiator) applyWebhookEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range p.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// WebhookInitiatorInterface is the interface specification for the webhook initiator.
type WebhookInitiatorInterface interface {
	// EventNotificationWithBody fires the eventNotification webhook with any body
	EventNotificationWithBody(ctx context.Context, targetURL string, params *EventNotificationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EventNotification(ctx context.Context, targetURL string, params *EventNotificationParams, body EventNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProgramUrlWithBody fires the getProgramUrl webhook with any body
	GetProgramUrlWithBody(ctx context.Context, targetURL string, params *GetProgramUrlParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetProgramUrl(ctx context.Context, targetURL string, params *GetProgramUrlParams, body GetProgramUrlJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProgramsWithBody fires the getPrograms webhook with any body
	GetProgramsWithBody(ctx context.Context, targetURL string, params *GetProgramsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetPrograms(ctx context.Context, targetURL string, params *GetProgramsParams, body GetProgramsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PreorderWithBody fires the preorder webhook with any body
	PreorderWithBody(ctx context.Context, targetURL string, params *PreorderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Preorder(ctx context.Context, targetURL string, params *PreorderParams, body PreorderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (p *WebhookInitiator) EventNotificationWithBody(ctx context.Context, targetURL string, params *EventNotificationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventNotificationWebhookRequestWithBody(targetURL, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) EventNotification(ctx context.Context, targetURL string, params *EventNotificationParams, body EventNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventNotificationWebhookRequest(targetURL, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) GetProgramUrlWithBody(ctx context.Context, targetURL string, params *GetProgramUrlParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProgramUrlWebhookRequestWithBody(targetURL, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) GetProgramUrl(ctx context.Context, targetURL string, params *GetProgramUrlParams, body GetProgramUrlJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProgramUrlWebhookRequest(targetURL, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) GetProgramsWithBody(ctx context.Context, targetURL string, params *GetProgramsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProgramsWebhookRequestWithBody(targetURL, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) GetPrograms(ctx context.Context, targetURL string, params *GetProgramsParams, body GetProgramsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProgramsWebhookRequest(targetURL, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) PreorderWithBody(ctx context.Context, targetURL string, params *PreorderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPreorderWebhookRequestWithBody(targetURL, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

func (p *WebhookInitiator) Preorder(ctx context.Context, targetURL string, params *PreorderParams, body PreorderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPreorderWebhookRequest(targetURL, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyWebhookEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

// NewEventNotificationWebhookRequest builds a application/json POST request for the eventNotification webhook
func NewEventNotificationWebhookRequest(targetURL string, params *EventNotificationParams, body EventNotificationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEventNotificationWebhookRequestWithBody(targetURL, params, "application/json", bodyReader)
}

// NewEventNotificationWebhookRequestWithBody builds a POST request for the eventNotification webhook with any body
func NewEventNotificationWebhookRequestWithBody(targetURL string, params *EventNotificationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error
	_ = err

	reqURL, err := url.Parse(targetURL)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		if params.XXealthToken != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Xealth-Token", *params.XXealthToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Xealth-Token", headerParam1)
		}

	}
	return req, nil
}

// NewGetProgramUrlWebhookRequest builds a application/json PUT request for the getProgramUrl webhook
func NewGetProgramUrlWebhookRequest(targetURL string, params *GetProgramUrlParams, body GetProgramUrlJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetProgramUrlWebhookRequestWithBody(targetURL, params, "application/json", bodyReader)
}

// NewGetProgramUrlWebhookRequestWithBody builds a PUT request for the getProgramUrl webhook with any body
func NewGetProgramUrlWebhookRequestWithBody(targetURL string, params *GetProgramUrlParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error
	_ = err

	reqURL, err := url.Parse(targetURL)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		if params.XXealthToken != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Xealth-Token", *params.XXealthToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Xealth-Token", headerParam1)
		}

	}
	return req, nil
}

// NewGetProgramsWebhookRequest builds a application/json PUT request for the getPrograms webhook
func NewGetProgramsWebhookRequest(targetURL string, params *GetProgramsParams, body GetProgramsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetProgramsWebhookRequestWithBody(targetURL, params, "application/json", bodyReader)
}

// NewGetProgramsWebhookRequestWithBody builds a PUT request for the getPrograms webhook with any body
func NewGetProgramsWebhookRequestWithBody(targetURL string, params *GetProgramsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error
	_ = err

	reqURL, err := url.Parse(targetURL)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		if params.XXealthToken != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Xealth-Token", *params.XXealthToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Xealth-Token", headerParam1)
		}

	}
	return req, nil
}

// NewPreorderWebhookRequest builds a application/json POST request for the preorder webhook
func NewPreorderWebhookRequest(targetURL string, params *PreorderParams, body PreorderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPreorderWebhookRequestWithBody(targetURL, params, "application/json", bodyReader)
}

// NewPreorderWebhookRequestWithBody builds a POST request for the preorder webhook with any body
func NewPreorderWebhookRequestWithBody(targetURL string, params *PreorderParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error
	_ = err

	reqURL, err := url.Parse(targetURL)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam0)

		if params.XXealthToken != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Xealth-Token", *params.XXealthToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Xealth-Token", headerParam1)
		}

	}
	return req, nil
}
