// Code generated by MockGen. DO NOT EDIT.
// Source: ./custodial.go
//
// Generated by this command:
//
//	mockgen -source=./custodial.go -destination=./mock_custodial_service.go -package service CustodialService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	patients "github.com/tidepool-org/clinic/patients"
	gomock "go.uber.org/mock/gomock"
)

// MockCustodialService is a mock of CustodialService interface.
type MockCustodialService struct {
	ctrl     *gomock.Controller
	recorder *MockCustodialServiceMockRecorder
	isgomock struct{}
}

// MockCustodialServiceMockRecorder is the mock recorder for MockCustodialService.
type MockCustodialServiceMockRecorder struct {
	mock *MockCustodialService
}

// NewMockCustodialService creates a new mock instance.
func NewMockCustodialService(ctrl *gomock.Controller) *MockCustodialService {
	mock := &MockCustodialService{ctrl: ctrl}
	mock.recorder = &MockCustodialServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustodialService) EXPECT() *MockCustodialServiceMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockCustodialService) CreateAccount(ctx context.Context, patient patients.Patient) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, patient)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockCustodialServiceMockRecorder) CreateAccount(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockCustodialService)(nil).CreateAccount), ctx, patient)
}

// DeleteAccount mocks base method.
func (m *MockCustodialService) DeleteAccount(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockCustodialServiceMockRecorder) DeleteAccount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockCustodialService)(nil).DeleteAccount), ctx, userID)
}

// UpdateAccount mocks base method.
func (m *MockCustodialService) UpdateAccount(ctx context.Context, patient patients.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockCustodialServiceMockRecorder) UpdateAccount(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockCustodialService)(nil).UpdateAccount), ctx, patient)
}
