// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pruneScheduledSummaryReportsOrders = `-- name: PruneScheduledSummaryReportsOrders :execrows
DELETE FROM scheduled_summary_reports_orders
WHERE created_time < $1
`

func (q *Queries) PruneScheduledSummaryReportsOrders(ctx context.Context, createdTime pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneScheduledSummaryReportsOrders, createdTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRedoxMessage = `-- name: UpsertRedoxMessage :exec
INSERT INTO redox_messages (
    id, meta_data_model, meta_event_type, meta_source_id, meta_source_name,
    meta_facility_code, meta_log_ids, payload, pg_synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (id) DO UPDATE SET
    meta_data_model = EXCLUDED.meta_data_model,
    meta_event_type = EXCLUDED.meta_event_type,
    meta_source_id = EXCLUDED.meta_source_id,
    meta_source_name = EXCLUDED.meta_source_name,
    meta_facility_code = EXCLUDED.meta_facility_code,
    meta_log_ids = EXCLUDED.meta_log_ids,
    payload = EXCLUDED.payload,
    pg_synced_at = now()
`

type UpsertRedoxMessageParams struct {
	ID               string
	MetaDataModel    string
	MetaEventType    string
	MetaSourceID     pgtype.Text
	MetaSourceName   pgtype.Text
	MetaFacilityCode pgtype.Text
	MetaLogIds       []string
	Payload          []byte
}

func (q *Queries) UpsertRedoxMessage(ctx context.Context, arg UpsertRedoxMessageParams) error {
	_, err := q.db.Exec(ctx, upsertRedoxMessage,
		arg.ID,
		arg.MetaDataModel,
		arg.MetaEventType,
		arg.MetaSourceID,
		arg.MetaSourceName,
		arg.MetaFacilityCode,
		arg.MetaLogIds,
		arg.Payload,
	)
	return err
}

const upsertScheduledSummaryReportsOrder = `-- name: UpsertScheduledSummaryReportsOrder :exec
INSERT INTO scheduled_summary_reports_orders (
    id, clinic_id, user_id, last_matched_order_id, created_time, payload, pg_synced_at
) VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    clinic_id = EXCLUDED.clinic_id,
    user_id = EXCLUDED.user_id,
    last_matched_order_id = EXCLUDED.last_matched_order_id,
    created_time = EXCLUDED.created_time,
    payload = EXCLUDED.payload,
    pg_synced_at = now()
`

type UpsertScheduledSummaryReportsOrderParams struct {
	ID                 string
	ClinicID           pgtype.Text
	UserID             pgtype.Text
	LastMatchedOrderID pgtype.Text
	CreatedTime        pgtype.Timestamptz
	Payload            []byte
}

func (q *Queries) UpsertScheduledSummaryReportsOrder(ctx context.Context, arg UpsertScheduledSummaryReportsOrderParams) error {
	_, err := q.db.Exec(ctx, upsertScheduledSummaryReportsOrder,
		arg.ID,
		arg.ClinicID,
		arg.UserID,
		arg.LastMatchedOrderID,
		arg.CreatedTime,
		arg.Payload,
	)
	return err
}
