root = "."
tmp_dir = "tmp"
testdata_dir = "test"

[build]
  pre_cmd = []
  cmd = "./build.sh"
  post_cmd = []
  bin = "./dist/clinic"
  full_bin = ""
  args_bin = []
  log = "build-errors.log"
  include_ext = ["go", "rego"]
  exclude_dir = ["clinicians/test", "clinics/test", "dist", "node_modules", "patients/test", "redox/test", "store/test", "test", "tmp", "tools", "vendor"]
  include_dir = []
  exclude_file = []
  include_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  poll = false
  poll_interval = 0
  delay = 2000
  stop_on_error = true
  send_interrupt = false
  kill_delay = 0
  rerun = false
  rerun_delay = 500

[log]
  time = false
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
  app = ""

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
