components:
  schemas:
    Clinic:
      allOf:
      - properties:
          _id:
            type: string
        required:
        - _id
        type: object
      - $ref: '#/components/schemas/NewClinic'
      title: Clinic
    ClinicianPermissions:
      description: Permisions for relationship between Clinics and Clinicians
      properties:
        permissions:
          items:
            pattern: CLINIC_ADMIN|CLINIC_CLINICIAN|CLINIC_PRESCRIBER
            type: string
          type: array
          uniqueItems: true
      title: ClinicianPermissions
      type: object
    ClinicsClinicians:
      allOf:
      - properties:
          clinicId:
            type: string
          clinicianId:
            type: string
        required:
        - clinicianId
        type: object
      - $ref: '#/components/schemas/ClinicianPermissions'
      description: Relationship between Clinics and Clinicians
      title: ClinicsClinicians
    ClinicsPatients:
      allOf:
      - properties:
          clinicId:
            type: string
          id:
            type: string
          patientId:
            type: string
        type: object
      - $ref: '#/components/schemas/PatientPermissions'
      description: Clinics Patients Relationship
      title: ClinicsPatients
    Error:
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      title: Error
      type: object
    NewClinic:
      description: Object describing a clinic
      properties:
        address:
          type: string
        location:
          type: string
        metadata:
          type: object
        name:
          minLength: 1
          type: string
        phoneNumbers:
          items:
            properties:
              number:
                type: string
              type:
                type: string
            type: object
          type: array
      title: NewClinic
      type: object
      x-examples:
        example:
          address: 3000 Main drive
          id: '5445'
          location: Walnut Creek
          metadata: {}
          name: John Muir
          phoneNumbers:
            number: 555-555-5555
            type: main
    PatientPermissions:
      description: Permissions for Clinic Patient Relationship
      properties:
        permissions:
          items:
            type: string
          type: array
      title: PatientPermissions
      type: object
  securitySchemes:
    ClinicAuth:
      flows:
        implicit:
          authorizationUrl: https://www.tidepool.org/auth
          refreshUrl: https://www.tidepool.org/refresh
          scopes:
            CLINIC_ADMIN: Clinic Administrator
            CLINIC_CLINICIAN: Clinician at Clinic
            CLINIC_PATIENT: Patient of Clinic
            CLINIC_PRESCRIBER: Clinician at Clinic with Prescriber Role
            TIDEPOOL_ADMIN: Tidepool Administrator
      type: oauth2
info:
  title: clinic
  version: '1.0'
openapi: 3.0.0
paths:
  /clinics:
    get:
      description: Retrieve list of clinics.  Requires admin app authorization
      operationId: get-clinics
      parameters:
      - description: ''
        in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Clinic'
                type: array
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
      summary: GetClinics
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
    parameters: []
    post:
      description: Add a new clinic
      operationId: post-clinics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClinic'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: AddClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
  /clinics/{clinicid}:
    delete:
      description: Delete Clinic
      operationId: delete-clinics-clinicid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: DeleteClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
    get:
      description: Get Clinic
      operationId: get-clinics-clinicid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clinic'
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
        - TIDEPOOL_ADMIN
      summary: GetClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    patch:
      description: Modify Clinic
      operationId: patch-clinics-clinicid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClinic'
          application/xml:
            schema:
              properties: {}
              type: object
        description: Modify Clinic object
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: ModifyClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
  /clinics/{clinicid}/clinicians:
    get:
      description: Retrieve a list of clinicians for a clinic
      operationId: get-clinics-clinicid-clinicians
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ClinicsClinicians'
                type: array
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      summary: GetCliniciansFromClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    post:
      description: Add a clinician to clinic
      operationId: post-clinics-clinicid-clinicians
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicsClinicians'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: AddClinicianToClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
  /clinics/{clinicid}/clinicians/{clinicianid}:
    delete:
      description: Remove association with clinic and clinician
      operationId: delete-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: DeleteClinicianFromClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
    get:
      description: Get a clinician object
      operationId: get-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicsClinicians'
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: GetClinician
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    - in: path
      name: clinicianid
      required: true
      schema:
        type: string
    patch:
      operationId: patch-clinics-clinicid-clinicians-clinicianid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicianPermissions'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      summary: ModifyClinicClinician
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
  /clinics/{clinicid}/patients:
    get:
      description: Get list of patients associated with clinic
      operationId: get-clinics-clinicid-patients
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ClinicsPatients'
                type: array
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      summary: GetPatientsForClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    post:
      description: Add patient to clinic
      operationId: post-clinics-clinicid-patients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicsPatients'
        description: ''
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      summary: AddPatientToClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
  /clinics/{clinicid}/patients/{patientid}:
    delete:
      description: delete patient from clinic
      operationId: delete-clinic-clinicid-patients-patientid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      summary: DeletePatientFromClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
    get:
      description: Get a patient from clinic
      operationId: get-clinics-clinicid-patients-patientid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicsPatients'
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      summary: GetPatientFromClinic
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    - in: path
      name: patientid
      required: true
      schema:
        type: string
    patch:
      description: Modify a patient from clinic
      operationId: patch-clinics-clinicid-patients-patientid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientPermissions'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security:
      - ClinicAuth:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      summary: ModifyClinicPatient
      tags: []
      x-roles:
      - TIDEPOOL_ADMIN
      - CLINIC_ADMIN
      - CLINIC_CLINICIAN
servers:
- url: http://localhost:8080
- description: ''
  url: https://dev1.dev.tidepool.org
- description: ''
  url: https://qa1.development.tidepool.org
- description: ''
  url: https://qa2.development.tidepool.org
- description: ''
  url: https://external.integration.tidepool.org
- description: ''
  url: https://api.tidepool.org
- description: ''
  url: http://dev1.dev.tidepool.org
