components:
  schemas:
    Clinic:
      allOf:
      - properties:
          _id:
            type: string
        required:
        - _id
        type: object
      - $ref: '#/components/schemas/NewClinic'
      title: Clinic
    NewClinic:
      description: Object describing a clinic
      properties:
        address:
          enum:
          - test
          type: string
        location:
          type: string
        metadata:
          type: object
        name:
          minLength: 1
          type: string
        phoneNumbers:
          items:
            properties:
              number:
                type: string
              type:
                type: string
            type: object
          type: array
      title: NewClinic
      type: object
      x-examples:
        example:
          address: 3000 Main drive
          id: '5445'
          location: Walnut Creek
          metadata: {}
          name: John Muir
          phoneNumbers:
            number: 555-555-5555
            type: main
info:
  title: clinic
  version: '1.0'
openapi: 3.0.0
paths:
  /clinic:
    post:
      description: Creates a Clinic
      operationId: post-clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClinic'
      responses:
        '200':
          description: OK
      summary: CreateClinic
      tags: []
  /clinic/{clinicid}:
    delete:
      description: Delete Clinic
      operationId: delete-clinic-clinicid
      responses:
        '200':
          description: OK
      summary: DeleteClinic
    get:
      operationId: get-clinic-clinicid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clinic'
          description: OK
      summary: GetClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    patch:
      description: Modify Clinic
      operationId: patch-clinic-clinicid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClinic'
          application/xml:
            schema:
              properties: {}
              type: object
        description: Modify Clinic object
      responses:
        '200':
          description: OK
      summary: ModifyClinic
  /clinic/{clinicid}/clinician/{clinicianid}:
    delete:
      description: Remove association with clinic and clinician
      operationId: delete-clinic-clinicid-clinician-clinicianid
      responses:
        '200':
          description: OK
      summary: DeleteClinicianForClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    - in: path
      name: clinicianid
      required: true
      schema:
        type: string
    post:
      description: Add a Clinician to a Clinic
      operationId: post-clinic-clinicid-clinician-clinicianid
      responses:
        '200':
          description: OK
      summary: AddClinicianToClinic
  /clinic/{clinicid}/patient/{patientid}:
    delete:
      description: delete patient from clinic
      operationId: delete-clinic-clinicid-patient-patientid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      summary: DeletePatientFromClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    - in: path
      name: patientid
      required: true
      schema:
        type: string
    post:
      description: Add patient to clinic
      operationId: post-clinic-clinicid-patient-patientid
      requestBody:
        content:
          application/json:
            schema:
              properties:
                clinicId:
                  type: string
                id:
                  type: string
                patientId:
                  type: string
                permissions:
                  items:
                    type: string
                  type: array
              title: PatientClinicRelationship
              type: object
      responses:
        '200':
          description: OK
      summary: AddPatientToClinic
  /clinic/{clinicid}/patients:
    get:
      description: Get list of patients associated with clinic
      operationId: get-clinic-clinicid-patients
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    email:
                      type: string
                    id:
                      type: string
                    pwhas:
                      type: string
                    userid:
                      type: string
                    username:
                      type: string
                  title: Patient
                  type: object
                type: array
          description: OK
      summary: GetCliniciansForClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
  /clinics:
    get:
      description: Retrieve list of clinics.  Requires admin app authorization
      operationId: get-clinics
      parameters:
      - description: ''
        in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      requestBody:
        description: ''
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Clinic'
                type: array
          description: OK
      summary: GetClinic
      tags: []
    parameters: []
  /clinics/{clinicid}/clinicians:
    get:
      description: Retrieve a list of clinicians for a clinic
      operationId: get-clinics-clinicid-clinicians
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  description: Object describing a doctor
                  properties:
                    email:
                      type: string
                    id:
                      type: string
                    pwhash:
                      type: string
                    userid:
                      type: string
                    username:
                      type: string
                  title: Clinician
                  type: object
                type: array
          description: OK
      summary: GetCliniciansForClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
servers:
- url: http://localhost:3000
