openapi: 3.0.0
info:
  title: clinic
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /clinics:
    get:
      summary: GetClinics
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D/get/responses/200/content/application~1json/schema'
      operationId: get-clinics
      description: Retrieve list of clinics.  Requires admin app authorization
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: ''
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
    parameters: []
    post:
      summary: AddClinic
      operationId: post-clinics
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              title: NewClinic
              type: object
              x-examples:
                example:
                  id: '5445'
                  name: John Muir
                  address: 3000 Main drive
                  phoneNumbers:
                    type: main
                    number: 555-555-5555
                  location: Walnut Creek
                  metadata: {}
              description: Object describing a clinic
              properties:
                name:
                  type: string
                  minLength: 1
                address:
                  type: string
                  enum:
                    - test
                phoneNumbers:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      number:
                        type: string
                location:
                  type: string
                metadata:
                  type: object
      description: Add a new clinic
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
  '/clinics/{clinicid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      _id:
                        type: string
                    required:
                      - _id
                  - $ref: '#/paths/~1clinics/post/requestBody/content/application~1json/schema'
                title: Clinic
      operationId: get-clinics-clinicid
      description: Get Clinic
      security:
        - ClinicAuth:
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
            - TIDEPOOL_ADMIN
    patch:
      summary: ModifyClinic
      operationId: patch-clinics-clinicid
      responses:
        '200':
          description: OK
      description: Modify Clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1clinics/post/requestBody/content/application~1json/schema'
          application/xml:
            schema:
              type: object
              properties: {}
        description: Modify Clinic object
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
    delete:
      summary: DeleteClinic
      operationId: delete-clinics-clinicid
      responses:
        '200':
          description: OK
      description: Delete Clinic
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
  '/clinics/{clinicid}/clinicians/{clinicianid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: clinicianid
        in: path
        required: true
    delete:
      summary: DeleteClinicianFromClinic
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-clinics-clinicid-clinicians-clinicianid
      description: Remove association with clinic and clinician
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
    patch:
      summary: ModifyClinicClinician
      operationId: patch-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              title: ClinicianPermissions
              type: object
              properties:
                permissions:
                  type: array
                  uniqueItems: true
                  items:
                    type: string
                    pattern: 'Admin|Prescriber|Clinician'
              description: Permisions for relationship between Clinics and Clinicians
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
    get:
      summary: GetClinician
      operationId: get-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians/post/requestBody/content/application~1json/schema'
      description: Get a clinician object
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
  '/clinics/{clinicid}/patients':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetPatientsForClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients/post/requestBody/content/application~1json/schema'
      operationId: get-clinics-clinicid-patients
      description: Get list of patients associated with clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    post:
      summary: AddPatientToClinic
      operationId: post-clinics-clinicid-patients
      responses:
        '200':
          description: OK
      description: Add patient to clinic
      requestBody:
        content:
          application/json:
            schema:
              title: ClinicsPatients
              allOf:
                - type: object
                  properties:
                    id:
                      type: string
                    patientId:
                      type: string
                    clinicId:
                      type: string
                - $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients~1%7Bpatientid%7D/patch/requestBody/content/application~1json/schema'
              description: Clinics Patients Relationship
        description: ''
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
  '/clinics/{clinicid}/patients/{patientid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: patientid
        in: path
        required: true
    delete:
      summary: DeletePatientFromClinic
      tags: []
      operationId: delete-clinic-clinicid-patients-patientid
      description: delete patient from clinic
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    get:
      summary: GetPatientFromClinic
      operationId: get-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients/post/requestBody/content/application~1json/schema'
      description: Get a patient from clinic
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    patch:
      summary: ModifyClinicPatient
      operationId: patch-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
      description: Modify a patient from clinic
      requestBody:
        content:
          application/json:
            schema:
              title: PatientPermissions
              type: object
              properties:
                permissions:
                  type: array
                  items:
                    type: string
              description: Permissions for Clinic Patient Relationship
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
  '/clinics/{clinicid}/clinicians':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetCliniciansFromClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians/post/requestBody/content/application~1json/schema'
      operationId: get-clinics-clinicid-clinicians
      description: Retrieve a list of clinicians for a clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    post:
      summary: AddClinicianToClinic
      operationId: post-clinics-clinicid-clinicians
      responses:
        '200':
          description: OK
      description: Add a clinician to clinic
      requestBody:
        content:
          application/json:
            schema:
              title: ClinicsClinicians
              allOf:
                - type: object
                  properties:
                    clinicianId:
                      type: string
                    clinicId:
                      type: string
                  required:
                    - clinicianId
                - $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians~1%7Bclinicianid%7D/patch/requestBody/content/application~1json/schema'
              description: Relationship between Clinics and Clinicians
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
components:
  schemas: {}
  securitySchemes:
    ClinicAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://www.tidepool.org/auth'
          scopes:
            TIDEPOOL_ADMIN: Tidepool Administrator
            CLINIC_ADMIN: Clinic Administrator
            CLINIC_CLINICIAN: Clinician at Clinic
            CLINIC_PATIENT: Patient of Clinic
            CLINIC_PRESCRIBER: Clinician at Clinic with Prescriber Role
          refreshUrl: 'https://www.tidepool.org/refresh'
