openapi: 3.0.0
info:
  title: clinic
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
  - url: 'https://dev1.dev.tidepool.org'
    description: ''
  - url: 'https://qa1.development.tidepool.org'
    description: ''
  - url: 'https://qa2.development.tidepool.org'
    description: ''
  - url: 'https://external.integration.tidepool.org'
    description: ''
  - url: 'https://api.tidepool.org'
    description: ''
  - url: 'http://dev1.dev.tidepool.org'
    description: ''
paths:
  /clinics:
    get:
      summary: GetClinics
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D/get/responses/200/content/application~1json/schema'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                title: Error
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                required:
                  - code
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/paths/~1clinics/get/responses/400/content/application~1json/schema'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/paths/~1clinics/get/responses/400/content/application~1json/schema'
      operationId: get-clinics
      description: Retrieve list of clinics.  Requires admin app authorization
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: ''
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
        - schema:
            type: string
          in: query
          name: clinicianId
        - schema:
            type: string
          in: query
          name: patientId
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
    parameters: []
    post:
      summary: AddClinic
      operationId: post-clinics
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: PostClinicResponse
                type: object
                description: Response from a call to post clinic endpoint
                properties:
                  clinicId:
                    type: string
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1clinics~1%7Bclinicid%7D/patch/requestBody/content/application~1json/schema'
      description: Add a new clinic
      security: []
      x-roles: []
      tags: []
      parameters:
        - schema:
            type: string
          in: header
          name: X-TIDEPOOL-USERID
          description: Userid for endpoint
  '/clinics/{clinicid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      _id:
                        type: string
                    required:
                      - _id
                  - $ref: '#/paths/~1clinics~1%7Bclinicid%7D/patch/requestBody/content/application~1json/schema'
                title: Clinic
          links:
            get-clinicians:
              operationId: get-clinics-clinicid-clinicians
              parameters:
                clinicid: $request.query.clinicid
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-clinics-clinicid
      description: Get Clinic
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
    patch:
      summary: ModifyClinic
      operationId: patch-clinics-clinicid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Modify Clinic
      requestBody:
        content:
          application/json:
            schema:
              title: NewClinic
              type: object
              x-examples:
                example:
                  id: '5445'
                  name: John Muir
                  address: 3000 Main drive
                  phoneNumbers:
                    type: main
                    number: 555-555-5555
                  location: Walnut Creek
                  metadata: {}
              description: Object describing a clinic
              properties:
                name:
                  type: string
                  minLength: 1
                address:
                  type: string
                city:
                  type: string
                postalCode:
                  type: string
                state:
                  type: string
                country:
                  type: string
                phoneNumbers:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      number:
                        type: string
                metadata:
                  type: object
                  properties:
                    data:
                      type: string
                clinicType:
                  type: string
                clinicSize:
                  type: integer
          application/xml:
            schema:
              type: object
              properties: {}
        description: Modify Clinic object
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      tags: []
    delete:
      summary: DeleteClinic
      operationId: delete-clinics-clinicid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Delete Clinic
      security: []
      tags: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
  '/clinics/{clinicid}/clinicians/{clinicianid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: clinicianid
        in: path
        required: true
    delete:
      summary: DeleteClinicianFromClinic
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: delete-clinics-clinicid-clinicians-clinicianid
      description: Remove association with clinic and clinician
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
    patch:
      summary: ModifyClinicClinician
      description: update clinic clinician relationship
      operationId: patch-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              title: ClinicianPermissions
              type: object
              description: Permisions for relationship between Clinics and Clinicians
              properties:
                permissions:
                  type: array
                  uniqueItems: true
                  items:
                    type: string
                    pattern: 'CLINIC_ADMIN|CLINIC_CLINICIAN|CLINIC_PRESCRIBER'
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      tags: []
    get:
      summary: GetClinician
      operationId: get-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians/post/requestBody/content/application~1json/schema'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Get a clinician object
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      tags: []
  '/clinics/{clinicid}/patients':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetPatientsForClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients/post/requestBody/content/application~1json/schema'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-clinics-clinicid-patients
      description: Get list of patients associated with clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
    post:
      summary: AddPatientToClinic
      operationId: post-clinics-clinicid-patients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: PatientPostId
                type: object
                properties:
                  id:
                    type: string
                description: Id of newly create patient/clinic relationship
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Add patient to clinic
      requestBody:
        content:
          application/json:
            schema:
              title: ClinicsPatients
              allOf:
                - type: object
                  properties:
                    id:
                      type: string
                    patientId:
                      type: string
                    clinicId:
                      type: string
                - $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients~1%7Bpatientid%7D/patch/requestBody/content/application~1json/schema'
              description: Clinics Patients Relationship
        description: ''
      security: []
      tags: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
  '/clinics/{clinicid}/patients/{patientid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: patientid
        in: path
        required: true
    delete:
      summary: DeletePatientFromClinic
      tags: []
      operationId: delete-clinic-clinicid-patients-patientid
      description: delete patient from clinic
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
    get:
      summary: GetPatientFromClinic
      operationId: get-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients/post/requestBody/content/application~1json/schema'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Get a patient from clinic
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      tags: []
    patch:
      summary: ModifyClinicPatient
      operationId: patch-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Modify a patient from clinic
      requestBody:
        content:
          application/json:
            schema:
              title: PatientPermissions
              type: object
              properties:
                permissions:
                  type: array
                  items:
                    type: string
              description: Permissions for Clinic Patient Relationship
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
      tags: []
  '/clinics/{clinicid}/clinicians':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetCliniciansFromClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians/post/requestBody/content/application~1json/schema'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-clinics-clinicid-clinicians
      description: Retrieve a list of clinicians for a clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
        - CLINIC_CLINICIAN
    post:
      summary: AddClinicianToClinic
      operationId: post-clinics-clinicid-clinicians
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: CliniciansPostId
                type: object
                properties:
                  id:
                    type: string
                description: Id of newly created clinician/clinic relationship
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Add a clinician to clinic
      requestBody:
        content:
          application/json:
            schema:
              title: ClinicsClinicians
              allOf:
                - type: object
                  properties:
                    clinicianId:
                      type: string
                    clinicId:
                      type: string
                  required:
                    - clinicianId
                - $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians~1%7Bclinicianid%7D/patch/requestBody/content/application~1json/schema'
              description: Relationship between Clinics and Clinicians
      security: []
      x-roles:
        - TIDEPOOL_ADMIN
        - CLINIC_ADMIN
      tags: []
  '/clinics/patients/{patientid}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1patients/post/requestBody/content/application~1json/schema'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-clinics-patients-patientid
      description: Retrieves information on patients in any of the clinics
      x-roles:
        - TIDEPOOL_ADMIN
    delete:
      summary: ''
      tags: []
      description: Delete patient from all clinics
      operationId: delete-clinics-patients-patientid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      x-roles:
        - TIDEPOOL_ADMIN
    parameters:
      - schema:
          type: string
        name: patientid
        in: path
        required: true
  '/clinics/clinicians/{clinicianid}':
    parameters:
      - schema:
          type: string
        name: clinicianid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1clinics~1%7Bclinicid%7D~1clinicians/post/requestBody/content/application~1json/schema'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      operationId: get-clinics-clinicians-clinicianid
      description: Gets Clinicians from all clinics
      x-roles:
        - TIDEPOOL_ADMIN
    delete:
      summary: ''
      tags: []
      operationId: delete-clinics-clinicians-clinicianid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      description: Deletes clinician from all clinics
      x-roles:
        - TIDEPOOL_ADMIN
components:
  schemas: {}
  securitySchemes: {}
