components:
  schemas:
    Clinic:
      allOf:
      - properties:
          _id:
            type: string
        required:
        - _id
        type: object
      - $ref: '#/components/schemas/NewClinic'
      title: Clinic
    ClinicianPermissions:
      properties:
        permissions:
          items:
            pattern: Admin|Prescriber|Clinician
            type: string
          type: array
          uniqueItems: true
      title: ClinicianPermissions
      type: object
    ClinicsClinicians:
      allOf:
      - properties:
          clinicId:
            type: string
          clinicianId:
            type: string
        required:
        - clinicianId
        type: object
      - $ref: '#/components/schemas/ClinicianPermissions'
      title: ClinicsClinicians
    ClinicsPatients:
      properties:
        clinicId:
          type: string
        id:
          type: string
        patientId:
          type: string
        permissions:
          items:
            type: string
          type: array
      title: ClinicsPatients
      type: object
    NewClinic:
      description: Object describing a clinic
      properties:
        address:
          enum:
          - test
          type: string
        location:
          type: string
        metadata:
          type: object
        name:
          minLength: 1
          type: string
        phoneNumbers:
          items:
            properties:
              number:
                type: string
              type:
                type: string
            type: object
          type: array
      title: NewClinic
      type: object
      x-examples:
        example:
          address: 3000 Main drive
          id: '5445'
          location: Walnut Creek
          metadata: {}
          name: John Muir
          phoneNumbers:
            number: 555-555-5555
            type: main
info:
  title: clinic
  version: '1.0'
openapi: 3.0.0
paths:
  /clinics:
    get:
      description: Retrieve list of clinics.  Requires admin app authorization
      operationId: get-clinics
      parameters:
      - description: ''
        in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Clinic'
                type: array
          description: OK
      summary: GetClinics
      tags: []
    parameters: []
    post:
      description: Add a new clinic
      operationId: post-clinics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClinic'
      responses:
        '200':
          description: OK
      summary: AddClinic
  /clinics/{clinicid}:
    delete:
      description: Delete Clinic
      operationId: delete-clinics-clinicid
      responses:
        '200':
          description: OK
      summary: DeleteClinic
    get:
      description: Get Clinic
      operationId: get-clinics-clinicid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clinic'
          description: OK
      summary: GetClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    patch:
      description: Modify Clinic
      operationId: patch-clinics-clinicid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClinic'
          application/xml:
            schema:
              properties: {}
              type: object
        description: Modify Clinic object
      responses:
        '200':
          description: OK
      summary: ModifyClinic
  /clinics/{clinicid}/clinicians:
    get:
      description: Retrieve a list of clinicians for a clinic
      operationId: get-clinics-clinicid-clinicians
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ClinicsClinicians'
                type: array
          description: OK
      summary: GetCliniciansFromClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    post:
      description: Add a clinician to clinic
      operationId: post-clinics-clinicid-clinicians
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicsClinicians'
      responses:
        '200':
          description: OK
      summary: AddClinicianToClinic
  /clinics/{clinicid}/clinicians/{clinicianid}:
    delete:
      description: Remove association with clinic and clinician
      operationId: delete-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
      summary: DeleteClinicianFromClinic
      tags: []
    get:
      description: Get a clinician object
      operationId: get-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClinicsClinicians'
          description: OK
      summary: GetClinician
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    - in: path
      name: clinicianid
      required: true
      schema:
        type: string
    patch:
      operationId: patch-clinics-clinicid-clinicians-clinicianid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicianPermissions'
      responses:
        '200':
          description: OK
      summary: ModifyClinicClinician
  /clinics/{clinicid}/patients:
    get:
      description: Get list of patients associated with clinic
      operationId: get-clinics-clinicid-patients
      parameters:
      - in: query
        name: offset
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: sortOrder
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ClinicsPatients'
                type: array
          description: OK
      summary: GetPatientsForClinic
      tags: []
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    post:
      description: Add patient to clinic
      operationId: post-clinics-clinicid-patients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClinicsPatients'
      responses:
        '200':
          description: OK
      summary: AddPatientToClinic
  /clinics/{clinicid}/patients/{patientid}:
    delete:
      description: delete patient from clinic
      operationId: delete-clinic-clinicid-patient-patientid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      summary: DeletePatientFromClinic
      tags: []
    get:
      description: Get a patient from clinic
      operationId: get-clinics-clinicid-patient-patientid
      responses:
        '200':
          description: OK
      summary: GetPatientFromClinic
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    - in: path
      name: patientid
      required: true
      schema:
        type: string
    patch:
      description: Modify a patient from clinic
      operationId: patch-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
      summary: ModifyClinicPatient
servers:
- url: http://localhost:3000
