SHELL = /bin/sh

TOOLS_BIN = tools/bin
NPM_BIN = node_modules/.bin

OAPI_CODEGEN = $(TOOLS_BIN)/oapi-codegen
MOCKGEN = $(TOOLS_BIN)/mockgen
SWAGGER_CLI = $(NPM_BIN)/swagger-cli
OPENAPI_FILTER = $(NPM_BIN)/openapi-filter
GINKGO = go run -mod=mod github.com/onsi/ginkgo/v2/ginkgo

NPM_PKG_SPECS = \
	@apidevtools/swagger-cli@^4.0.4 \
	openapi-filter@^3.2.3

PATH:=$(shell pwd)/$(TOOLS_BIN):$(PATH)

OSTYPE:=$(shell echo $${OSTYPE})

# this can also be removed once sed usage is removed from generate
# switch to bsd-friendly sed for macos/darwin
ifneq (,$(findstring darwin,$(OSTYPE)))
  INPLACE_SED = sed -i ''
else
  INPLACE_SED = sed -i
endif

# Generates server files
.PHONY: generate
generate: $(SWAGGER_CLI) $(OAPI_CODEGEN) $(MOCKGEN)
	$(SWAGGER_CLI) bundle ../TidepoolApi/reference/clinic.v1.yaml -o ./spec/clinic.v1.yaml -t yaml
	$(OAPI_CODEGEN) -exclude-tags=Confirmations -package=api -generate=server spec/clinic.v1.yaml > api/gen_server.go
	$(OAPI_CODEGEN) -exclude-tags=Confirmations -package=api -generate=spec spec/clinic.v1.yaml > api/gen_spec.go
	$(OAPI_CODEGEN) -exclude-tags=Confirmations -package=api -generate=types spec/clinic.v1.yaml > api/gen_types.go
	$(OAPI_CODEGEN) -exclude-tags=Confirmations -package=client -generate=types spec/clinic.v1.yaml > client/types.go
	$(OAPI_CODEGEN) -exclude-tags=Confirmations -package=client -generate=client spec/clinic.v1.yaml > client/client.go
	$(SWAGGER_CLI) bundle ../TidepoolApi/reference/redox.v1.yaml -o ./spec/redox.v1.yaml -t yaml
	$(OAPI_CODEGEN) -package=redox_models -generate=types spec/redox.v1.yaml > redox_models/gen_types.go
	$(OAPI_CODEGEN) -include-tags="Orders (Partner)",Webhooks -package=xealth_client -generate=types,skip-prune ../TidepoolApi/reference/xealth.v2.yaml > xealth_client/gen_types.go
	$(OAPI_CODEGEN) -include-tags="Orders (Partner)" -package=xealth_client -generate=client ../TidepoolApi/reference/xealth.v2.yaml > xealth_client/gen_client.go
	go generate ./...
	# the following can be removed once this uncommented warning is no longer generated by oapi-codegen
	$(INPLACE_SED) 's/^[\/\/]*WARNING: You are using an OpenAPI 3\.1\.x specification, which is not yet supported by oapi-codegen/\/\/ &/' ./xealth_client/gen*.go
	cd client && go generate ./...

# Generate linkerd service profile
service-profile/profile.yaml: service-profile/clinic.v1.yaml service-profile
	linkerd profile --ignore-cluster --open-api service-profile/clinic.v1.yaml clinic > service-profile/profile.yaml

service-profile/clinic.v1.yaml: $(OPENAPI_FILTER) generate service-profile
	$(OPENAPI_FILTER) -f Confirmations --checkTags spec/clinic.v1.yaml service-profile/clinic.v1.yaml

service-profile:
	mkdir -p service-profile

# Set flags
.PHONY: go-flags
go-flags:
	go env -w GOFLAGS=-mod=mod

# Runs tests
.PHONY: test
test:
	$(GINKGO) run --require-suite --compilers=2 -r --randomize-suites --randomize-all --succinct --fail-on-pending --trace --race --poll-progress-after=10s --poll-progress-interval=20s --keep-going ./...

# Builds package
.PHONY: build
build: go-flags
	./build.sh

$(OAPI_CODEGEN):
	GOBIN=$(shell pwd)/$(TOOLS_BIN) go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1

$(MOCKGEN):
	GOBIN=$(shell pwd)/$(TOOLS_BIN) go install go.uber.org/mock/mockgen@v0.5.0

$(SWAGGER_CLI): npm-tools

$(OPENAPI_FILTER): npm-tools

.PHONY: npm-tools
npm-tools:
# When using --no-save, any dependencies not included will be deleted, so one
# has to install all the packages all at the same time. But it saves us from
# having to muck with packages.json.
	npm install --no-save --local $(NPM_PKG_SPECS)

.PHONY: clean
clean:
	rm -rf dist node_modules tools

.PHONY: ci-generate
ci-generate: generate

.PHONY: ci-build
ci-build: build

.PHONY: ci-test
ci-test: test
