// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	UpsertMigration(ctx context.Context, arg UpsertMigrationParams) error
}

var _ Querier = (*Queries)(nil)
