-- +goose Up
CREATE TABLE patient_summaries (
    patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    summary_type text NOT NULL CHECK (summary_type IN ('cgm', 'bgm')),
    -- The platform summary id; DeleteSummaryInAllClinics looks summaries up
    -- by it
    summary_id text NOT NULL,
    config_schema_version integer NOT NULL,
    config_high_glucose_threshold double precision NOT NULL,
    config_low_glucose_threshold double precision NOT NULL,
    config_very_high_glucose_threshold double precision NOT NULL,
    config_very_low_glucose_threshold double precision NOT NULL,
    dates_first_data timestamptz,
    dates_has_first_data boolean NOT NULL DEFAULT false,
    dates_has_last_data boolean NOT NULL DEFAULT false,
    dates_has_last_upload_date boolean NOT NULL DEFAULT false,
    dates_has_outdated_since boolean NOT NULL DEFAULT false,
    dates_last_data timestamptz,
    dates_last_updated_date timestamptz,
    dates_last_updated_reason text[],
    dates_last_upload_date timestamptz,
    dates_outdated_reason text[],
    dates_outdated_since timestamptz,
    dates_outdated_since_limit timestamptz,
    pg_synced_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (patient_id, summary_type)
);

CREATE INDEX patient_summaries_summary_id_idx ON patient_summaries (summary_id);
CREATE INDEX patient_summaries_last_data_idx ON patient_summaries (summary_type, dates_last_data);

-- The superset of CGM and BGM metrics as typed nullable columns; metrics the
-- summary type doesn't track stay NULL
CREATE TABLE patient_summary_periods (
    patient_id text NOT NULL,
    summary_type text NOT NULL,
    -- No CHECK on the period keys: the API accepts summaries with arbitrary
    -- period keys (the spec's period maps allow additional properties), and a
    -- constraint violation here would permanently stop the whole patient row
    -- from syncing and abort backfills.
    period text NOT NULL,
    average_daily_records double precision,
    average_daily_records_delta double precision,
    average_glucose_mmol double precision,
    average_glucose_mmol_delta double precision,
    coefficient_of_variation double precision,
    coefficient_of_variation_delta double precision,
    days_with_data integer,
    days_with_data_delta integer,
    glucose_management_indicator double precision,
    glucose_management_indicator_delta double precision,
    has_average_daily_records boolean,
    has_average_glucose_mmol boolean,
    has_glucose_management_indicator boolean,
    has_time_cgm_use_minutes boolean,
    has_time_cgm_use_percent boolean,
    has_time_cgm_use_records boolean,
    has_time_in_any_high_minutes boolean,
    has_time_in_any_high_percent boolean,
    has_time_in_any_high_records boolean,
    has_time_in_any_low_minutes boolean,
    has_time_in_any_low_percent boolean,
    has_time_in_any_low_records boolean,
    has_time_in_extreme_high_minutes boolean,
    has_time_in_extreme_high_percent boolean,
    has_time_in_extreme_high_records boolean,
    has_time_in_high_minutes boolean,
    has_time_in_high_percent boolean,
    has_time_in_high_records boolean,
    has_time_in_low_minutes boolean,
    has_time_in_low_percent boolean,
    has_time_in_low_records boolean,
    has_time_in_target_minutes boolean,
    has_time_in_target_percent boolean,
    has_time_in_target_records boolean,
    has_time_in_very_high_minutes boolean,
    has_time_in_very_high_percent boolean,
    has_time_in_very_high_records boolean,
    has_time_in_very_low_minutes boolean,
    has_time_in_very_low_percent boolean,
    has_time_in_very_low_records boolean,
    has_total_records boolean,
    hours_with_data integer,
    hours_with_data_delta integer,
    max double precision,
    max_delta double precision,
    min double precision,
    min_delta double precision,
    standard_deviation double precision,
    standard_deviation_delta double precision,
    time_cgm_use_minutes integer,
    time_cgm_use_minutes_delta integer,
    time_cgm_use_percent double precision,
    time_cgm_use_percent_delta double precision,
    time_cgm_use_records integer,
    time_cgm_use_records_delta integer,
    time_in_any_high_minutes integer,
    time_in_any_high_minutes_delta integer,
    time_in_any_high_percent double precision,
    time_in_any_high_percent_delta double precision,
    time_in_any_high_records integer,
    time_in_any_high_records_delta integer,
    time_in_any_low_minutes integer,
    time_in_any_low_minutes_delta integer,
    time_in_any_low_percent double precision,
    time_in_any_low_percent_delta double precision,
    time_in_any_low_records integer,
    time_in_any_low_records_delta integer,
    time_in_extreme_high_minutes integer,
    time_in_extreme_high_minutes_delta integer,
    time_in_extreme_high_percent double precision,
    time_in_extreme_high_percent_delta double precision,
    time_in_extreme_high_records integer,
    time_in_extreme_high_records_delta integer,
    time_in_high_minutes integer,
    time_in_high_minutes_delta integer,
    time_in_high_percent double precision,
    time_in_high_percent_delta double precision,
    time_in_high_records integer,
    time_in_high_records_delta integer,
    time_in_low_minutes integer,
    time_in_low_minutes_delta integer,
    time_in_low_percent double precision,
    time_in_low_percent_delta double precision,
    time_in_low_records integer,
    time_in_low_records_delta integer,
    time_in_target_minutes integer,
    time_in_target_minutes_delta integer,
    time_in_target_percent double precision,
    time_in_target_percent_delta double precision,
    time_in_target_records integer,
    time_in_target_records_delta integer,
    time_in_very_high_minutes integer,
    time_in_very_high_minutes_delta integer,
    time_in_very_high_percent double precision,
    time_in_very_high_percent_delta double precision,
    time_in_very_high_records integer,
    time_in_very_high_records_delta integer,
    time_in_very_low_minutes integer,
    time_in_very_low_minutes_delta integer,
    time_in_very_low_percent double precision,
    time_in_very_low_percent_delta double precision,
    time_in_very_low_records integer,
    time_in_very_low_records_delta integer,
    total_records integer,
    total_records_delta integer,
    PRIMARY KEY (patient_id, summary_type, period),
    FOREIGN KEY (patient_id, summary_type)
        REFERENCES patient_summaries (patient_id, summary_type) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE patient_summary_periods;
DROP TABLE patient_summaries;
