// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clinics.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClinic = `-- name: DeleteClinic :exec
DELETE FROM clinics WHERE id = $1
`

func (q *Queries) DeleteClinic(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteClinic, id)
	return err
}

const deleteClinicAdmins = `-- name: DeleteClinicAdmins :exec
DELETE FROM clinic_admins WHERE clinic_id = $1
`

func (q *Queries) DeleteClinicAdmins(ctx context.Context, clinicID string) error {
	_, err := q.db.Exec(ctx, deleteClinicAdmins, clinicID)
	return err
}

const deleteClinicMembershipRestrictions = `-- name: DeleteClinicMembershipRestrictions :exec
DELETE FROM clinic_membership_restrictions WHERE clinic_id = $1
`

func (q *Queries) DeleteClinicMembershipRestrictions(ctx context.Context, clinicID string) error {
	_, err := q.db.Exec(ctx, deleteClinicMembershipRestrictions, clinicID)
	return err
}

const deleteClinicPatientTags = `-- name: DeleteClinicPatientTags :exec
DELETE FROM clinic_patient_tags WHERE clinic_id = $1
`

func (q *Queries) DeleteClinicPatientTags(ctx context.Context, clinicID string) error {
	_, err := q.db.Exec(ctx, deleteClinicPatientTags, clinicID)
	return err
}

const deleteClinicPhoneNumbers = `-- name: DeleteClinicPhoneNumbers :exec
DELETE FROM clinic_phone_numbers WHERE clinic_id = $1
`

func (q *Queries) DeleteClinicPhoneNumbers(ctx context.Context, clinicID string) error {
	_, err := q.db.Exec(ctx, deleteClinicPhoneNumbers, clinicID)
	return err
}

const deleteClinicShareCodes = `-- name: DeleteClinicShareCodes :exec
DELETE FROM clinic_share_codes WHERE clinic_id = $1
`

func (q *Queries) DeleteClinicShareCodes(ctx context.Context, clinicID string) error {
	_, err := q.db.Exec(ctx, deleteClinicShareCodes, clinicID)
	return err
}

const deleteClinicSites = `-- name: DeleteClinicSites :exec
DELETE FROM clinic_sites WHERE clinic_id = $1
`

func (q *Queries) DeleteClinicSites(ctx context.Context, clinicID string) error {
	_, err := q.db.Exec(ctx, deleteClinicSites, clinicID)
	return err
}

const insertClinicAdmin = `-- name: InsertClinicAdmin :exec
INSERT INTO clinic_admins (clinic_id, user_id)
VALUES ($1, $2)
ON CONFLICT (clinic_id, user_id) DO NOTHING
`

type InsertClinicAdminParams struct {
	ClinicID string
	UserID   string
}

func (q *Queries) InsertClinicAdmin(ctx context.Context, arg InsertClinicAdminParams) error {
	_, err := q.db.Exec(ctx, insertClinicAdmin, arg.ClinicID, arg.UserID)
	return err
}

const insertClinicMembershipRestriction = `-- name: InsertClinicMembershipRestriction :exec
INSERT INTO clinic_membership_restrictions (clinic_id, email_domain, required_idp)
VALUES ($1, $2, $3)
ON CONFLICT (clinic_id, email_domain) DO UPDATE SET
    required_idp = EXCLUDED.required_idp
`

type InsertClinicMembershipRestrictionParams struct {
	ClinicID    string
	EmailDomain string
	RequiredIdp pgtype.Text
}

func (q *Queries) InsertClinicMembershipRestriction(ctx context.Context, arg InsertClinicMembershipRestrictionParams) error {
	_, err := q.db.Exec(ctx, insertClinicMembershipRestriction, arg.ClinicID, arg.EmailDomain, arg.RequiredIdp)
	return err
}

const insertClinicPatientTag = `-- name: InsertClinicPatientTag :exec
INSERT INTO clinic_patient_tags (id, clinic_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    clinic_id = EXCLUDED.clinic_id,
    name = EXCLUDED.name
`

type InsertClinicPatientTagParams struct {
	ID       string
	ClinicID string
	Name     string
}

func (q *Queries) InsertClinicPatientTag(ctx context.Context, arg InsertClinicPatientTagParams) error {
	_, err := q.db.Exec(ctx, insertClinicPatientTag, arg.ID, arg.ClinicID, arg.Name)
	return err
}

const insertClinicPhoneNumber = `-- name: InsertClinicPhoneNumber :exec
INSERT INTO clinic_phone_numbers (clinic_id, ordinal, type, number)
VALUES ($1, $2, $3, $4)
ON CONFLICT (clinic_id, ordinal) DO UPDATE SET
    type = EXCLUDED.type,
    number = EXCLUDED.number
`

type InsertClinicPhoneNumberParams struct {
	ClinicID string
	Ordinal  int32
	Type     pgtype.Text
	Number   string
}

func (q *Queries) InsertClinicPhoneNumber(ctx context.Context, arg InsertClinicPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, insertClinicPhoneNumber,
		arg.ClinicID,
		arg.Ordinal,
		arg.Type,
		arg.Number,
	)
	return err
}

const insertClinicShareCode = `-- name: InsertClinicShareCode :exec
INSERT INTO clinic_share_codes (share_code, clinic_id)
VALUES ($1, $2)
ON CONFLICT (share_code) DO UPDATE SET clinic_id = EXCLUDED.clinic_id
`

type InsertClinicShareCodeParams struct {
	ShareCode string
	ClinicID  string
}

func (q *Queries) InsertClinicShareCode(ctx context.Context, arg InsertClinicShareCodeParams) error {
	_, err := q.db.Exec(ctx, insertClinicShareCode, arg.ShareCode, arg.ClinicID)
	return err
}

const insertClinicSite = `-- name: InsertClinicSite :exec
INSERT INTO clinic_sites (id, clinic_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    clinic_id = EXCLUDED.clinic_id,
    name = EXCLUDED.name
`

type InsertClinicSiteParams struct {
	ID       string
	ClinicID string
	Name     string
}

func (q *Queries) InsertClinicSite(ctx context.Context, arg InsertClinicSiteParams) error {
	_, err := q.db.Exec(ctx, insertClinicSite, arg.ID, arg.ClinicID, arg.Name)
	return err
}

const upsertClinic = `-- name: UpsertClinic :exec
INSERT INTO clinics (
    id, name, address, city, state, postal_code, country, clinic_type,
    clinic_size, website, timezone, preferred_bg_units, canonical_share_code,
    tier, is_migrated, created_time, updated_time,
    suppress_patient_clinic_invitation, mrn_required, mrn_unique,
    ehr_enabled, ehr_provider, ehr_source_id, ehr_mrn_id_type,
    ehr_destination_flowsheet, ehr_destination_notes, ehr_destination_results,
    ehr_procedure_enable_summary_reports, ehr_procedure_disable_summary_reports,
    ehr_procedure_create_account, ehr_procedure_create_account_and_enable_reports,
    ehr_scheduled_reports_cadence, ehr_scheduled_reports_on_upload_enabled,
    ehr_scheduled_reports_on_upload_note_event_type,
    ehr_tags_codes, ehr_tags_separator, ehr_flowsheets_icode, ehr_notes_include_gmi,
    pcs_hard_limit_plan, pcs_hard_limit_start_date, pcs_hard_limit_end_date,
    pcs_hard_limit_legacy_patient_count,
    pcs_soft_limit_plan, pcs_soft_limit_start_date, pcs_soft_limit_end_date,
    pcs_soft_limit_legacy_patient_count,
    patient_count_total, patient_count_demo, patient_count_plan,
    patient_count_legacy, patient_count_providers, pg_synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44,
    $45, $46, $47, $48, $49, $50, $51, now()
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    postal_code = EXCLUDED.postal_code,
    country = EXCLUDED.country,
    clinic_type = EXCLUDED.clinic_type,
    clinic_size = EXCLUDED.clinic_size,
    website = EXCLUDED.website,
    timezone = EXCLUDED.timezone,
    preferred_bg_units = EXCLUDED.preferred_bg_units,
    canonical_share_code = EXCLUDED.canonical_share_code,
    tier = EXCLUDED.tier,
    is_migrated = EXCLUDED.is_migrated,
    created_time = EXCLUDED.created_time,
    updated_time = EXCLUDED.updated_time,
    suppress_patient_clinic_invitation = EXCLUDED.suppress_patient_clinic_invitation,
    mrn_required = EXCLUDED.mrn_required,
    mrn_unique = EXCLUDED.mrn_unique,
    ehr_enabled = EXCLUDED.ehr_enabled,
    ehr_provider = EXCLUDED.ehr_provider,
    ehr_source_id = EXCLUDED.ehr_source_id,
    ehr_mrn_id_type = EXCLUDED.ehr_mrn_id_type,
    ehr_destination_flowsheet = EXCLUDED.ehr_destination_flowsheet,
    ehr_destination_notes = EXCLUDED.ehr_destination_notes,
    ehr_destination_results = EXCLUDED.ehr_destination_results,
    ehr_procedure_enable_summary_reports = EXCLUDED.ehr_procedure_enable_summary_reports,
    ehr_procedure_disable_summary_reports = EXCLUDED.ehr_procedure_disable_summary_reports,
    ehr_procedure_create_account = EXCLUDED.ehr_procedure_create_account,
    ehr_procedure_create_account_and_enable_reports = EXCLUDED.ehr_procedure_create_account_and_enable_reports,
    ehr_scheduled_reports_cadence = EXCLUDED.ehr_scheduled_reports_cadence,
    ehr_scheduled_reports_on_upload_enabled = EXCLUDED.ehr_scheduled_reports_on_upload_enabled,
    ehr_scheduled_reports_on_upload_note_event_type = EXCLUDED.ehr_scheduled_reports_on_upload_note_event_type,
    ehr_tags_codes = EXCLUDED.ehr_tags_codes,
    ehr_tags_separator = EXCLUDED.ehr_tags_separator,
    ehr_flowsheets_icode = EXCLUDED.ehr_flowsheets_icode,
    ehr_notes_include_gmi = EXCLUDED.ehr_notes_include_gmi,
    pcs_hard_limit_plan = EXCLUDED.pcs_hard_limit_plan,
    pcs_hard_limit_start_date = EXCLUDED.pcs_hard_limit_start_date,
    pcs_hard_limit_end_date = EXCLUDED.pcs_hard_limit_end_date,
    pcs_hard_limit_legacy_patient_count = EXCLUDED.pcs_hard_limit_legacy_patient_count,
    pcs_soft_limit_plan = EXCLUDED.pcs_soft_limit_plan,
    pcs_soft_limit_start_date = EXCLUDED.pcs_soft_limit_start_date,
    pcs_soft_limit_end_date = EXCLUDED.pcs_soft_limit_end_date,
    pcs_soft_limit_legacy_patient_count = EXCLUDED.pcs_soft_limit_legacy_patient_count,
    patient_count_total = EXCLUDED.patient_count_total,
    patient_count_demo = EXCLUDED.patient_count_demo,
    patient_count_plan = EXCLUDED.patient_count_plan,
    patient_count_legacy = EXCLUDED.patient_count_legacy,
    patient_count_providers = EXCLUDED.patient_count_providers,
    pg_synced_at = now()
`

type UpsertClinicParams struct {
	ID                                        string
	Name                                      pgtype.Text
	Address                                   pgtype.Text
	City                                      pgtype.Text
	State                                     pgtype.Text
	PostalCode                                pgtype.Text
	Country                                   pgtype.Text
	ClinicType                                pgtype.Text
	ClinicSize                                pgtype.Text
	Website                                   pgtype.Text
	Timezone                                  pgtype.Text
	PreferredBgUnits                          pgtype.Text
	CanonicalShareCode                        pgtype.Text
	Tier                                      pgtype.Text
	IsMigrated                                bool
	CreatedTime                               pgtype.Timestamptz
	UpdatedTime                               pgtype.Timestamptz
	SuppressPatientClinicInvitation           pgtype.Bool
	MrnRequired                               pgtype.Bool
	MrnUnique                                 pgtype.Bool
	EhrEnabled                                pgtype.Bool
	EhrProvider                               pgtype.Text
	EhrSourceID                               pgtype.Text
	EhrMrnIDType                              pgtype.Text
	EhrDestinationFlowsheet                   pgtype.Text
	EhrDestinationNotes                       pgtype.Text
	EhrDestinationResults                     pgtype.Text
	EhrProcedureEnableSummaryReports          pgtype.Text
	EhrProcedureDisableSummaryReports         pgtype.Text
	EhrProcedureCreateAccount                 pgtype.Text
	EhrProcedureCreateAccountAndEnableReports pgtype.Text
	EhrScheduledReportsCadence                pgtype.Text
	EhrScheduledReportsOnUploadEnabled        pgtype.Bool
	EhrScheduledReportsOnUploadNoteEventType  pgtype.Text
	EhrTagsCodes                              []string
	EhrTagsSeparator                          pgtype.Text
	EhrFlowsheetsIcode                        pgtype.Bool
	EhrNotesIncludeGmi                        pgtype.Bool
	PcsHardLimitPlan                          pgtype.Int4
	PcsHardLimitStartDate                     pgtype.Timestamptz
	PcsHardLimitEndDate                       pgtype.Timestamptz
	PcsHardLimitLegacyPatientCount            pgtype.Int4
	PcsSoftLimitPlan                          pgtype.Int4
	PcsSoftLimitStartDate                     pgtype.Timestamptz
	PcsSoftLimitEndDate                       pgtype.Timestamptz
	PcsSoftLimitLegacyPatientCount            pgtype.Int4
	PatientCountTotal                         pgtype.Int4
	PatientCountDemo                          pgtype.Int4
	PatientCountPlan                          pgtype.Int4
	PatientCountLegacy                        pgtype.Int4
	PatientCountProviders                     []byte
}

func (q *Queries) UpsertClinic(ctx context.Context, arg UpsertClinicParams) error {
	_, err := q.db.Exec(ctx, upsertClinic,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.ClinicType,
		arg.ClinicSize,
		arg.Website,
		arg.Timezone,
		arg.PreferredBgUnits,
		arg.CanonicalShareCode,
		arg.Tier,
		arg.IsMigrated,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.SuppressPatientClinicInvitation,
		arg.MrnRequired,
		arg.MrnUnique,
		arg.EhrEnabled,
		arg.EhrProvider,
		arg.EhrSourceID,
		arg.EhrMrnIDType,
		arg.EhrDestinationFlowsheet,
		arg.EhrDestinationNotes,
		arg.EhrDestinationResults,
		arg.EhrProcedureEnableSummaryReports,
		arg.EhrProcedureDisableSummaryReports,
		arg.EhrProcedureCreateAccount,
		arg.EhrProcedureCreateAccountAndEnableReports,
		arg.EhrScheduledReportsCadence,
		arg.EhrScheduledReportsOnUploadEnabled,
		arg.EhrScheduledReportsOnUploadNoteEventType,
		arg.EhrTagsCodes,
		arg.EhrTagsSeparator,
		arg.EhrFlowsheetsIcode,
		arg.EhrNotesIncludeGmi,
		arg.PcsHardLimitPlan,
		arg.PcsHardLimitStartDate,
		arg.PcsHardLimitEndDate,
		arg.PcsHardLimitLegacyPatientCount,
		arg.PcsSoftLimitPlan,
		arg.PcsSoftLimitStartDate,
		arg.PcsSoftLimitEndDate,
		arg.PcsSoftLimitLegacyPatientCount,
		arg.PatientCountTotal,
		arg.PatientCountDemo,
		arg.PatientCountPlan,
		arg.PatientCountLegacy,
		arg.PatientCountProviders,
	)
	return err
}
