// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertClinicDeletion = `-- name: UpsertClinicDeletion :exec
INSERT INTO clinic_deletions (id, deleted_time, deleted_by_user_id, clinic_id, payload, pg_synced_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE
SET deleted_time = EXCLUDED.deleted_time,
    deleted_by_user_id = EXCLUDED.deleted_by_user_id,
    clinic_id = EXCLUDED.clinic_id,
    payload = EXCLUDED.payload,
    pg_synced_at = now()
`

type UpsertClinicDeletionParams struct {
	ID              string
	DeletedTime     pgtype.Timestamptz
	DeletedByUserID pgtype.Text
	ClinicID        pgtype.Text
	Payload         []byte
}

func (q *Queries) UpsertClinicDeletion(ctx context.Context, arg UpsertClinicDeletionParams) error {
	_, err := q.db.Exec(ctx, upsertClinicDeletion,
		arg.ID,
		arg.DeletedTime,
		arg.DeletedByUserID,
		arg.ClinicID,
		arg.Payload,
	)
	return err
}

const upsertClinicianDeletion = `-- name: UpsertClinicianDeletion :exec
INSERT INTO clinician_deletions (id, deleted_time, deleted_by_user_id, clinic_id, user_id, payload, pg_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE
SET deleted_time = EXCLUDED.deleted_time,
    deleted_by_user_id = EXCLUDED.deleted_by_user_id,
    clinic_id = EXCLUDED.clinic_id,
    user_id = EXCLUDED.user_id,
    payload = EXCLUDED.payload,
    pg_synced_at = now()
`

type UpsertClinicianDeletionParams struct {
	ID              string
	DeletedTime     pgtype.Timestamptz
	DeletedByUserID pgtype.Text
	ClinicID        pgtype.Text
	UserID          pgtype.Text
	Payload         []byte
}

func (q *Queries) UpsertClinicianDeletion(ctx context.Context, arg UpsertClinicianDeletionParams) error {
	_, err := q.db.Exec(ctx, upsertClinicianDeletion,
		arg.ID,
		arg.DeletedTime,
		arg.DeletedByUserID,
		arg.ClinicID,
		arg.UserID,
		arg.Payload,
	)
	return err
}

const upsertPatientDeletion = `-- name: UpsertPatientDeletion :exec
INSERT INTO patient_deletions (id, deleted_time, deleted_by_user_id, clinic_id, user_id, payload, pg_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE
SET deleted_time = EXCLUDED.deleted_time,
    deleted_by_user_id = EXCLUDED.deleted_by_user_id,
    clinic_id = EXCLUDED.clinic_id,
    user_id = EXCLUDED.user_id,
    payload = EXCLUDED.payload,
    pg_synced_at = now()
`

type UpsertPatientDeletionParams struct {
	ID              string
	DeletedTime     pgtype.Timestamptz
	DeletedByUserID pgtype.Text
	ClinicID        pgtype.Text
	UserID          pgtype.Text
	Payload         []byte
}

func (q *Queries) UpsertPatientDeletion(ctx context.Context, arg UpsertPatientDeletionParams) error {
	_, err := q.db.Exec(ctx, upsertPatientDeletion,
		arg.ID,
		arg.DeletedTime,
		arg.DeletedByUserID,
		arg.ClinicID,
		arg.UserID,
		arg.Payload,
	)
	return err
}
