// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertMigration = `-- name: UpsertMigration :exec
INSERT INTO migrations (user_id, clinic_id, status, created_time, updated_time, pg_synced_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id) DO UPDATE
SET clinic_id = EXCLUDED.clinic_id,
    status = EXCLUDED.status,
    created_time = EXCLUDED.created_time,
    updated_time = EXCLUDED.updated_time,
    pg_synced_at = now()
`

type UpsertMigrationParams struct {
	UserID      string
	ClinicID    string
	Status      string
	CreatedTime pgtype.Timestamptz
	UpdatedTime pgtype.Timestamptz
}

func (q *Queries) UpsertMigration(ctx context.Context, arg UpsertMigrationParams) error {
	_, err := q.db.Exec(ctx, upsertMigration,
		arg.UserID,
		arg.ClinicID,
		arg.Status,
		arg.CreatedTime,
		arg.UpdatedTime,
	)
	return err
}
