// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PgsyncBackfillProgress struct {
	Collection string
	LastID     string
	UpdatedAt  pgtype.Timestamptz
}
