// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Clinic struct {
	ID                                        string
	Name                                      pgtype.Text
	Address                                   pgtype.Text
	City                                      pgtype.Text
	State                                     pgtype.Text
	PostalCode                                pgtype.Text
	Country                                   pgtype.Text
	ClinicType                                pgtype.Text
	ClinicSize                                pgtype.Text
	Website                                   pgtype.Text
	Timezone                                  pgtype.Text
	PreferredBgUnits                          pgtype.Text
	CanonicalShareCode                        pgtype.Text
	Tier                                      pgtype.Text
	IsMigrated                                bool
	CreatedTime                               pgtype.Timestamptz
	UpdatedTime                               pgtype.Timestamptz
	SuppressPatientClinicInvitation           pgtype.Bool
	MrnRequired                               pgtype.Bool
	MrnUnique                                 pgtype.Bool
	EhrEnabled                                pgtype.Bool
	EhrProvider                               pgtype.Text
	EhrSourceID                               pgtype.Text
	EhrMrnIDType                              pgtype.Text
	EhrDestinationFlowsheet                   pgtype.Text
	EhrDestinationNotes                       pgtype.Text
	EhrDestinationResults                     pgtype.Text
	EhrProcedureEnableSummaryReports          pgtype.Text
	EhrProcedureDisableSummaryReports         pgtype.Text
	EhrProcedureCreateAccount                 pgtype.Text
	EhrProcedureCreateAccountAndEnableReports pgtype.Text
	EhrScheduledReportsCadence                pgtype.Text
	EhrScheduledReportsOnUploadEnabled        pgtype.Bool
	EhrScheduledReportsOnUploadNoteEventType  pgtype.Text
	EhrTagsCodes                              []string
	EhrTagsSeparator                          pgtype.Text
	EhrFlowsheetsIcode                        pgtype.Bool
	EhrNotesIncludeGmi                        pgtype.Bool
	PcsHardLimitPlan                          pgtype.Int4
	PcsHardLimitStartDate                     pgtype.Timestamptz
	PcsHardLimitEndDate                       pgtype.Timestamptz
	PcsHardLimitLegacyPatientCount            pgtype.Int4
	PcsSoftLimitPlan                          pgtype.Int4
	PcsSoftLimitStartDate                     pgtype.Timestamptz
	PcsSoftLimitEndDate                       pgtype.Timestamptz
	PcsSoftLimitLegacyPatientCount            pgtype.Int4
	PatientCountTotal                         pgtype.Int4
	PatientCountDemo                          pgtype.Int4
	PatientCountPlan                          pgtype.Int4
	PatientCountLegacy                        pgtype.Int4
	PatientCountProviders                     []byte
	PgSyncedAt                                pgtype.Timestamptz
}

type ClinicAdmin struct {
	ClinicID string
	UserID   string
}

type ClinicDeletion struct {
	ID              string
	DeletedTime     pgtype.Timestamptz
	DeletedByUserID pgtype.Text
	ClinicID        pgtype.Text
	Payload         []byte
	PgSyncedAt      pgtype.Timestamptz
}

type ClinicMembershipRestriction struct {
	ClinicID    string
	EmailDomain string
	RequiredIdp pgtype.Text
}

type ClinicPatientTag struct {
	ID       string
	ClinicID string
	Name     string
}

type ClinicPhoneNumber struct {
	ClinicID string
	Ordinal  int32
	Type     pgtype.Text
	Number   string
}

type ClinicShareCode struct {
	ShareCode string
	ClinicID  string
}

type ClinicSite struct {
	ID       string
	ClinicID string
	Name     string
}

type Clinician struct {
	ID               string
	ClinicID         string
	UserID           pgtype.Text
	Email            pgtype.Text
	FullName         pgtype.Text
	InviteID         pgtype.Text
	Roles            []string
	IsServiceAccount bool
	CreatedTime      pgtype.Timestamptz
	UpdatedTime      pgtype.Timestamptz
	SearchVector     interface{}
	PgSyncedAt       pgtype.Timestamptz
}

type ClinicianDeletion struct {
	ID              string
	DeletedTime     pgtype.Timestamptz
	DeletedByUserID pgtype.Text
	ClinicID        pgtype.Text
	UserID          pgtype.Text
	Payload         []byte
	PgSyncedAt      pgtype.Timestamptz
}

type ClinicianRolesUpdate struct {
	ClinicianID string
	Ordinal     int32
	Roles       []string
	UpdatedBy   pgtype.Text
}

type MergePlan struct {
	ID          string
	PlanID      string
	Type        string
	Payload     []byte
	CreatedTime pgtype.Timestamptz
	PgSyncedAt  pgtype.Timestamptz
}

type Migration struct {
	UserID      string
	ClinicID    string
	Status      string
	CreatedTime pgtype.Timestamptz
	UpdatedTime pgtype.Timestamptz
	PgSyncedAt  pgtype.Timestamptz
}

type Patient struct {
	ID                             string
	ClinicID                       string
	UserID                         string
	FullName                       pgtype.Text
	FullNameNormalized             pgtype.Text
	BirthDate                      pgtype.Text
	Email                          pgtype.Text
	Mrn                            pgtype.Text
	RequireUniqueMrn               bool
	IsMigrated                     bool
	InvitedBy                      pgtype.Text
	DiagnosisType                  pgtype.Text
	TargetDevices                  []string
	LegacyClinicianIds             []string
	PermCustodian                  bool
	PermView                       bool
	PermUpload                     bool
	PermNote                       bool
	GlycemicRangesType             pgtype.Text
	GlycemicRangesPreset           pgtype.Text
	GlycemicRangesCustom           []byte
	CreatedTime                    pgtype.Timestamptz
	UpdatedTime                    pgtype.Timestamptz
	LastUploadReminderTime         pgtype.Timestamptz
	LastRequestedDexcomConnectTime pgtype.Timestamptz
	PgSyncedAt                     pgtype.Timestamptz
}

type PatientDataSource struct {
	PatientID      string
	Ordinal        int32
	ProviderName   string
	State          string
	DataSourceID   pgtype.Text
	ModifiedTime   pgtype.Timestamptz
	ExpirationTime pgtype.Timestamptz
	LatestDataTime pgtype.Timestamptz
}

type PatientDeletion struct {
	ID              string
	DeletedTime     pgtype.Timestamptz
	DeletedByUserID pgtype.Text
	ClinicID        pgtype.Text
	UserID          pgtype.Text
	Payload         []byte
	PgSyncedAt      pgtype.Timestamptz
}

type PatientEhrSubscription struct {
	PatientID   string
	Name        string
	Provider    string
	Active      bool
	CreatedTime pgtype.Timestamptz
	UpdatedTime pgtype.Timestamptz
}

type PatientEhrSubscriptionMatchedMessage struct {
	PatientID        string
	SubscriptionName string
	Ordinal          int32
	MessageID        string
	DataModel        string
	EventType        string
}

type PatientProviderConnectionRequest struct {
	PatientID    string
	ProviderName string
	CreatedTime  pgtype.Timestamptz
}

type PatientReview struct {
	PatientID   string
	Ordinal     int32
	ClinicianID string
	ReviewTime  pgtype.Timestamptz
}

type PatientSite struct {
	PatientID string
	SiteID    string
	SiteName  string
}

type PatientSummary struct {
	PatientID                      string
	SummaryType                    string
	SummaryID                      string
	ConfigSchemaVersion            int32
	ConfigHighGlucoseThreshold     float64
	ConfigLowGlucoseThreshold      float64
	ConfigVeryHighGlucoseThreshold float64
	ConfigVeryLowGlucoseThreshold  float64
	DatesFirstData                 pgtype.Timestamptz
	DatesHasFirstData              bool
	DatesHasLastData               bool
	DatesHasLastUploadDate         bool
	DatesHasOutdatedSince          bool
	DatesLastData                  pgtype.Timestamptz
	DatesLastUpdatedDate           pgtype.Timestamptz
	DatesLastUpdatedReason         []string
	DatesLastUploadDate            pgtype.Timestamptz
	DatesOutdatedReason            []string
	DatesOutdatedSince             pgtype.Timestamptz
	DatesOutdatedSinceLimit        pgtype.Timestamptz
	PgSyncedAt                     pgtype.Timestamptz
}

type PatientSummaryPeriod struct {
	PatientID                       string
	SummaryType                     string
	Period                          string
	AverageDailyRecords             pgtype.Float8
	AverageDailyRecordsDelta        pgtype.Float8
	AverageGlucoseMmol              pgtype.Float8
	AverageGlucoseMmolDelta         pgtype.Float8
	CoefficientOfVariation          pgtype.Float8
	CoefficientOfVariationDelta     pgtype.Float8
	DaysWithData                    pgtype.Int4
	DaysWithDataDelta               pgtype.Int4
	GlucoseManagementIndicator      pgtype.Float8
	GlucoseManagementIndicatorDelta pgtype.Float8
	HasAverageDailyRecords          pgtype.Bool
	HasAverageGlucoseMmol           pgtype.Bool
	HasGlucoseManagementIndicator   pgtype.Bool
	HasTimeCgmUseMinutes            pgtype.Bool
	HasTimeCgmUsePercent            pgtype.Bool
	HasTimeCgmUseRecords            pgtype.Bool
	HasTimeInAnyHighMinutes         pgtype.Bool
	HasTimeInAnyHighPercent         pgtype.Bool
	HasTimeInAnyHighRecords         pgtype.Bool
	HasTimeInAnyLowMinutes          pgtype.Bool
	HasTimeInAnyLowPercent          pgtype.Bool
	HasTimeInAnyLowRecords          pgtype.Bool
	HasTimeInExtremeHighMinutes     pgtype.Bool
	HasTimeInExtremeHighPercent     pgtype.Bool
	HasTimeInExtremeHighRecords     pgtype.Bool
	HasTimeInHighMinutes            pgtype.Bool
	HasTimeInHighPercent            pgtype.Bool
	HasTimeInHighRecords            pgtype.Bool
	HasTimeInLowMinutes             pgtype.Bool
	HasTimeInLowPercent             pgtype.Bool
	HasTimeInLowRecords             pgtype.Bool
	HasTimeInTargetMinutes          pgtype.Bool
	HasTimeInTargetPercent          pgtype.Bool
	HasTimeInTargetRecords          pgtype.Bool
	HasTimeInVeryHighMinutes        pgtype.Bool
	HasTimeInVeryHighPercent        pgtype.Bool
	HasTimeInVeryHighRecords        pgtype.Bool
	HasTimeInVeryLowMinutes         pgtype.Bool
	HasTimeInVeryLowPercent         pgtype.Bool
	HasTimeInVeryLowRecords         pgtype.Bool
	HasTotalRecords                 pgtype.Bool
	HoursWithData                   pgtype.Int4
	HoursWithDataDelta              pgtype.Int4
	Max                             pgtype.Float8
	MaxDelta                        pgtype.Float8
	Min                             pgtype.Float8
	MinDelta                        pgtype.Float8
	StandardDeviation               pgtype.Float8
	StandardDeviationDelta          pgtype.Float8
	TimeCgmUseMinutes               pgtype.Int4
	TimeCgmUseMinutesDelta          pgtype.Int4
	TimeCgmUsePercent               pgtype.Float8
	TimeCgmUsePercentDelta          pgtype.Float8
	TimeCgmUseRecords               pgtype.Int4
	TimeCgmUseRecordsDelta          pgtype.Int4
	TimeInAnyHighMinutes            pgtype.Int4
	TimeInAnyHighMinutesDelta       pgtype.Int4
	TimeInAnyHighPercent            pgtype.Float8
	TimeInAnyHighPercentDelta       pgtype.Float8
	TimeInAnyHighRecords            pgtype.Int4
	TimeInAnyHighRecordsDelta       pgtype.Int4
	TimeInAnyLowMinutes             pgtype.Int4
	TimeInAnyLowMinutesDelta        pgtype.Int4
	TimeInAnyLowPercent             pgtype.Float8
	TimeInAnyLowPercentDelta        pgtype.Float8
	TimeInAnyLowRecords             pgtype.Int4
	TimeInAnyLowRecordsDelta        pgtype.Int4
	TimeInExtremeHighMinutes        pgtype.Int4
	TimeInExtremeHighMinutesDelta   pgtype.Int4
	TimeInExtremeHighPercent        pgtype.Float8
	TimeInExtremeHighPercentDelta   pgtype.Float8
	TimeInExtremeHighRecords        pgtype.Int4
	TimeInExtremeHighRecordsDelta   pgtype.Int4
	TimeInHighMinutes               pgtype.Int4
	TimeInHighMinutesDelta          pgtype.Int4
	TimeInHighPercent               pgtype.Float8
	TimeInHighPercentDelta          pgtype.Float8
	TimeInHighRecords               pgtype.Int4
	TimeInHighRecordsDelta          pgtype.Int4
	TimeInLowMinutes                pgtype.Int4
	TimeInLowMinutesDelta           pgtype.Int4
	TimeInLowPercent                pgtype.Float8
	TimeInLowPercentDelta           pgtype.Float8
	TimeInLowRecords                pgtype.Int4
	TimeInLowRecordsDelta           pgtype.Int4
	TimeInTargetMinutes             pgtype.Int4
	TimeInTargetMinutesDelta        pgtype.Int4
	TimeInTargetPercent             pgtype.Float8
	TimeInTargetPercentDelta        pgtype.Float8
	TimeInTargetRecords             pgtype.Int4
	TimeInTargetRecordsDelta        pgtype.Int4
	TimeInVeryHighMinutes           pgtype.Int4
	TimeInVeryHighMinutesDelta      pgtype.Int4
	TimeInVeryHighPercent           pgtype.Float8
	TimeInVeryHighPercentDelta      pgtype.Float8
	TimeInVeryHighRecords           pgtype.Int4
	TimeInVeryHighRecordsDelta      pgtype.Int4
	TimeInVeryLowMinutes            pgtype.Int4
	TimeInVeryLowMinutesDelta       pgtype.Int4
	TimeInVeryLowPercent            pgtype.Float8
	TimeInVeryLowPercentDelta       pgtype.Float8
	TimeInVeryLowRecords            pgtype.Int4
	TimeInVeryLowRecordsDelta       pgtype.Int4
	TotalRecords                    pgtype.Int4
	TotalRecordsDelta               pgtype.Int4
}

type PatientTag struct {
	PatientID string
	TagID     string
}

type PgsyncBackfillProgress struct {
	Collection string
	LastID     string
	UpdatedAt  pgtype.Timestamptz
}

type RedoxMessage struct {
	ID               string
	MetaDataModel    string
	MetaEventType    string
	MetaSourceID     pgtype.Text
	MetaSourceName   pgtype.Text
	MetaFacilityCode pgtype.Text
	MetaLogIds       []string
	Payload          []byte
	PgSyncedAt       pgtype.Timestamptz
}

type ScheduledSummaryReportsOrder struct {
	ID                 string
	ClinicID           pgtype.Text
	UserID             pgtype.Text
	LastMatchedOrderID pgtype.Text
	CreatedTime        pgtype.Timestamptz
	Payload            []byte
	PgSyncedAt         pgtype.Timestamptz
}

type XealthOrder struct {
	ID         string
	Payload    []byte
	PgSyncedAt pgtype.Timestamptz
}

type XealthPreorder struct {
	ID             string
	DataTrackingID string
	Payload        []byte
	PgSyncedAt     pgtype.Timestamptz
}

type XealthReportView struct {
	ID            string
	UserID        string
	DeploymentID  string
	SystemLogin   pgtype.Text
	PatientUserID string
	ProgramID     string
	ClinicID      string
	CreatedTime   pgtype.Timestamptz
	PgSyncedAt    pgtype.Timestamptz
}
