// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteBackfillProgress(ctx context.Context, collection string) error
	GetBackfillProgress(ctx context.Context, collection string) (PgsyncBackfillProgress, error)
	UpsertBackfillProgress(ctx context.Context, arg UpsertBackfillProgressParams) error
}

var _ Querier = (*Queries)(nil)
