// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	UpsertClinicDeletion(ctx context.Context, arg UpsertClinicDeletionParams) error
	UpsertClinicianDeletion(ctx context.Context, arg UpsertClinicianDeletionParams) error
	UpsertPatientDeletion(ctx context.Context, arg UpsertPatientDeletionParams) error
}

var _ Querier = (*Queries)(nil)
