// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_plans.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertMergePlan = `-- name: UpsertMergePlan :exec
INSERT INTO merge_plans (id, plan_id, type, payload, created_time, pg_synced_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE
SET plan_id = EXCLUDED.plan_id,
    type = EXCLUDED.type,
    payload = EXCLUDED.payload,
    created_time = EXCLUDED.created_time,
    pg_synced_at = now()
`

type UpsertMergePlanParams struct {
	ID          string
	PlanID      string
	Type        string
	Payload     []byte
	CreatedTime pgtype.Timestamptz
}

func (q *Queries) UpsertMergePlan(ctx context.Context, arg UpsertMergePlanParams) error {
	_, err := q.db.Exec(ctx, upsertMergePlan,
		arg.ID,
		arg.PlanID,
		arg.Type,
		arg.Payload,
		arg.CreatedTime,
	)
	return err
}
