// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	UpsertMergePlan(ctx context.Context, arg UpsertMergePlanParams) error
}

var _ Querier = (*Queries)(nil)
