// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteClinic(ctx context.Context, id string) error
	DeleteClinicAdmins(ctx context.Context, clinicID string) error
	DeleteClinicMembershipRestrictions(ctx context.Context, clinicID string) error
	DeleteClinicPatientTags(ctx context.Context, clinicID string) error
	DeleteClinicPhoneNumbers(ctx context.Context, clinicID string) error
	DeleteClinicShareCodes(ctx context.Context, clinicID string) error
	DeleteClinicSites(ctx context.Context, clinicID string) error
	InsertClinicAdmin(ctx context.Context, arg InsertClinicAdminParams) error
	InsertClinicMembershipRestriction(ctx context.Context, arg InsertClinicMembershipRestrictionParams) error
	InsertClinicPatientTag(ctx context.Context, arg InsertClinicPatientTagParams) error
	InsertClinicPhoneNumber(ctx context.Context, arg InsertClinicPhoneNumberParams) error
	InsertClinicShareCode(ctx context.Context, arg InsertClinicShareCodeParams) error
	InsertClinicSite(ctx context.Context, arg InsertClinicSiteParams) error
	UpsertClinic(ctx context.Context, arg UpsertClinicParams) error
}

var _ Querier = (*Queries)(nil)
