// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteClinic(ctx context.Context, id string) error
	DeleteClinicAdmins(ctx context.Context, clinicID string) error
	DeleteClinicMembershipRestrictions(ctx context.Context, clinicID string) error
	DeleteClinicPatientTags(ctx context.Context, clinicID string) error
	DeleteClinicPhoneNumbers(ctx context.Context, clinicID string) error
	DeleteClinicShareCodes(ctx context.Context, clinicID string) error
	DeleteClinicSites(ctx context.Context, clinicID string) error
	InsertClinicAdmin(ctx context.Context, arg []InsertClinicAdminParams) *InsertClinicAdminBatchResults
	InsertClinicMembershipRestriction(ctx context.Context, arg []InsertClinicMembershipRestrictionParams) *InsertClinicMembershipRestrictionBatchResults
	InsertClinicPatientTag(ctx context.Context, arg []InsertClinicPatientTagParams) *InsertClinicPatientTagBatchResults
	InsertClinicPhoneNumber(ctx context.Context, arg []InsertClinicPhoneNumberParams) *InsertClinicPhoneNumberBatchResults
	InsertClinicShareCode(ctx context.Context, arg []InsertClinicShareCodeParams) *InsertClinicShareCodeBatchResults
	InsertClinicSite(ctx context.Context, arg []InsertClinicSiteParams) *InsertClinicSiteBatchResults
	UpsertClinic(ctx context.Context, arg UpsertClinicParams) error
}

var _ Querier = (*Queries)(nil)
