// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertPatientConnectionRequest = `-- name: InsertPatientConnectionRequest :batchexec
INSERT INTO patient_provider_connection_requests (patient_id, provider_name, created_time)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertPatientConnectionRequestBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientConnectionRequestParams struct {
	PatientID    string
	ProviderName string
	CreatedTime  pgtype.Timestamptz
}

func (q *Queries) InsertPatientConnectionRequest(ctx context.Context, arg []InsertPatientConnectionRequestParams) *InsertPatientConnectionRequestBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.ProviderName,
			a.CreatedTime,
		}
		batch.Queue(insertPatientConnectionRequest, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientConnectionRequestBatchResults{br, len(arg), false}
}

func (b *InsertPatientConnectionRequestBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientConnectionRequestBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientDataSource = `-- name: InsertPatientDataSource :batchexec
INSERT INTO patient_data_sources (
    patient_id, ordinal, provider_name, state, data_source_id,
    modified_time, expiration_time, latest_data_time
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPatientDataSourceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientDataSourceParams struct {
	PatientID      string
	Ordinal        int32
	ProviderName   string
	State          string
	DataSourceID   pgtype.Text
	ModifiedTime   pgtype.Timestamptz
	ExpirationTime pgtype.Timestamptz
	LatestDataTime pgtype.Timestamptz
}

func (q *Queries) InsertPatientDataSource(ctx context.Context, arg []InsertPatientDataSourceParams) *InsertPatientDataSourceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.Ordinal,
			a.ProviderName,
			a.State,
			a.DataSourceID,
			a.ModifiedTime,
			a.ExpirationTime,
			a.LatestDataTime,
		}
		batch.Queue(insertPatientDataSource, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientDataSourceBatchResults{br, len(arg), false}
}

func (b *InsertPatientDataSourceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientDataSourceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientEHRSubscription = `-- name: InsertPatientEHRSubscription :batchexec
INSERT INTO patient_ehr_subscriptions (patient_id, name, provider, active, created_time, updated_time)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPatientEHRSubscriptionBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientEHRSubscriptionParams struct {
	PatientID   string
	Name        string
	Provider    string
	Active      bool
	CreatedTime pgtype.Timestamptz
	UpdatedTime pgtype.Timestamptz
}

func (q *Queries) InsertPatientEHRSubscription(ctx context.Context, arg []InsertPatientEHRSubscriptionParams) *InsertPatientEHRSubscriptionBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.Name,
			a.Provider,
			a.Active,
			a.CreatedTime,
			a.UpdatedTime,
		}
		batch.Queue(insertPatientEHRSubscription, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientEHRSubscriptionBatchResults{br, len(arg), false}
}

func (b *InsertPatientEHRSubscriptionBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientEHRSubscriptionBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientEHRSubscriptionMatchedMessage = `-- name: InsertPatientEHRSubscriptionMatchedMessage :batchexec
INSERT INTO patient_ehr_subscription_matched_messages (
    patient_id, subscription_name, ordinal, message_id, data_model, event_type
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPatientEHRSubscriptionMatchedMessageBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientEHRSubscriptionMatchedMessageParams struct {
	PatientID        string
	SubscriptionName string
	Ordinal          int32
	MessageID        string
	DataModel        string
	EventType        string
}

func (q *Queries) InsertPatientEHRSubscriptionMatchedMessage(ctx context.Context, arg []InsertPatientEHRSubscriptionMatchedMessageParams) *InsertPatientEHRSubscriptionMatchedMessageBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.SubscriptionName,
			a.Ordinal,
			a.MessageID,
			a.DataModel,
			a.EventType,
		}
		batch.Queue(insertPatientEHRSubscriptionMatchedMessage, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientEHRSubscriptionMatchedMessageBatchResults{br, len(arg), false}
}

func (b *InsertPatientEHRSubscriptionMatchedMessageBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientEHRSubscriptionMatchedMessageBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientReview = `-- name: InsertPatientReview :batchexec
INSERT INTO patient_reviews (patient_id, ordinal, clinician_id, review_time)
VALUES ($1, $2, $3, $4)
`

type InsertPatientReviewBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientReviewParams struct {
	PatientID   string
	Ordinal     int32
	ClinicianID string
	ReviewTime  pgtype.Timestamptz
}

func (q *Queries) InsertPatientReview(ctx context.Context, arg []InsertPatientReviewParams) *InsertPatientReviewBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.Ordinal,
			a.ClinicianID,
			a.ReviewTime,
		}
		batch.Queue(insertPatientReview, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientReviewBatchResults{br, len(arg), false}
}

func (b *InsertPatientReviewBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientReviewBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientSite = `-- name: InsertPatientSite :batchexec
INSERT INTO patient_sites (patient_id, site_id, site_name)
VALUES ($1, $2, $3)
ON CONFLICT (patient_id, site_id) DO UPDATE SET site_name = EXCLUDED.site_name
`

type InsertPatientSiteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientSiteParams struct {
	PatientID string
	SiteID    string
	SiteName  string
}

func (q *Queries) InsertPatientSite(ctx context.Context, arg []InsertPatientSiteParams) *InsertPatientSiteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.SiteID,
			a.SiteName,
		}
		batch.Queue(insertPatientSite, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientSiteBatchResults{br, len(arg), false}
}

func (b *InsertPatientSiteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientSiteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientSummaryPeriod = `-- name: InsertPatientSummaryPeriod :batchexec
INSERT INTO patient_summary_periods (
    patient_id, summary_type, period, average_daily_records,
    average_daily_records_delta, average_glucose_mmol, average_glucose_mmol_delta, coefficient_of_variation,
    coefficient_of_variation_delta, days_with_data, days_with_data_delta, glucose_management_indicator,
    glucose_management_indicator_delta, has_average_daily_records, has_average_glucose_mmol, has_glucose_management_indicator,
    has_time_cgm_use_minutes, has_time_cgm_use_percent, has_time_cgm_use_records, has_time_in_any_high_minutes,
    has_time_in_any_high_percent, has_time_in_any_high_records, has_time_in_any_low_minutes, has_time_in_any_low_percent,
    has_time_in_any_low_records, has_time_in_extreme_high_minutes, has_time_in_extreme_high_percent, has_time_in_extreme_high_records,
    has_time_in_high_minutes, has_time_in_high_percent, has_time_in_high_records, has_time_in_low_minutes,
    has_time_in_low_percent, has_time_in_low_records, has_time_in_target_minutes, has_time_in_target_percent,
    has_time_in_target_records, has_time_in_very_high_minutes, has_time_in_very_high_percent, has_time_in_very_high_records,
    has_time_in_very_low_minutes, has_time_in_very_low_percent, has_time_in_very_low_records, has_total_records,
    hours_with_data, hours_with_data_delta, max, max_delta,
    min, min_delta, standard_deviation, standard_deviation_delta,
    time_cgm_use_minutes, time_cgm_use_minutes_delta, time_cgm_use_percent, time_cgm_use_percent_delta,
    time_cgm_use_records, time_cgm_use_records_delta, time_in_any_high_minutes, time_in_any_high_minutes_delta,
    time_in_any_high_percent, time_in_any_high_percent_delta, time_in_any_high_records, time_in_any_high_records_delta,
    time_in_any_low_minutes, time_in_any_low_minutes_delta, time_in_any_low_percent, time_in_any_low_percent_delta,
    time_in_any_low_records, time_in_any_low_records_delta, time_in_extreme_high_minutes, time_in_extreme_high_minutes_delta,
    time_in_extreme_high_percent, time_in_extreme_high_percent_delta, time_in_extreme_high_records, time_in_extreme_high_records_delta,
    time_in_high_minutes, time_in_high_minutes_delta, time_in_high_percent, time_in_high_percent_delta,
    time_in_high_records, time_in_high_records_delta, time_in_low_minutes, time_in_low_minutes_delta,
    time_in_low_percent, time_in_low_percent_delta, time_in_low_records, time_in_low_records_delta,
    time_in_target_minutes, time_in_target_minutes_delta, time_in_target_percent, time_in_target_percent_delta,
    time_in_target_records, time_in_target_records_delta, time_in_very_high_minutes, time_in_very_high_minutes_delta,
    time_in_very_high_percent, time_in_very_high_percent_delta, time_in_very_high_records, time_in_very_high_records_delta,
    time_in_very_low_minutes, time_in_very_low_minutes_delta, time_in_very_low_percent, time_in_very_low_percent_delta,
    time_in_very_low_records, time_in_very_low_records_delta, total_records, total_records_delta
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38, $39, $40,
    $41, $42, $43, $44, $45, $46, $47, $48, $49, $50,
    $51, $52, $53, $54, $55, $56, $57, $58, $59, $60,
    $61, $62, $63, $64, $65, $66, $67, $68, $69, $70,
    $71, $72, $73, $74, $75, $76, $77, $78, $79, $80,
    $81, $82, $83, $84, $85, $86, $87, $88, $89, $90,
    $91, $92, $93, $94, $95, $96, $97, $98, $99, $100,
    $101, $102, $103, $104, $105, $106, $107, $108
)
`

type InsertPatientSummaryPeriodBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientSummaryPeriodParams struct {
	PatientID                       string
	SummaryType                     string
	Period                          string
	AverageDailyRecords             pgtype.Float8
	AverageDailyRecordsDelta        pgtype.Float8
	AverageGlucoseMmol              pgtype.Float8
	AverageGlucoseMmolDelta         pgtype.Float8
	CoefficientOfVariation          pgtype.Float8
	CoefficientOfVariationDelta     pgtype.Float8
	DaysWithData                    pgtype.Int4
	DaysWithDataDelta               pgtype.Int4
	GlucoseManagementIndicator      pgtype.Float8
	GlucoseManagementIndicatorDelta pgtype.Float8
	HasAverageDailyRecords          pgtype.Bool
	HasAverageGlucoseMmol           pgtype.Bool
	HasGlucoseManagementIndicator   pgtype.Bool
	HasTimeCgmUseMinutes            pgtype.Bool
	HasTimeCgmUsePercent            pgtype.Bool
	HasTimeCgmUseRecords            pgtype.Bool
	HasTimeInAnyHighMinutes         pgtype.Bool
	HasTimeInAnyHighPercent         pgtype.Bool
	HasTimeInAnyHighRecords         pgtype.Bool
	HasTimeInAnyLowMinutes          pgtype.Bool
	HasTimeInAnyLowPercent          pgtype.Bool
	HasTimeInAnyLowRecords          pgtype.Bool
	HasTimeInExtremeHighMinutes     pgtype.Bool
	HasTimeInExtremeHighPercent     pgtype.Bool
	HasTimeInExtremeHighRecords     pgtype.Bool
	HasTimeInHighMinutes            pgtype.Bool
	HasTimeInHighPercent            pgtype.Bool
	HasTimeInHighRecords            pgtype.Bool
	HasTimeInLowMinutes             pgtype.Bool
	HasTimeInLowPercent             pgtype.Bool
	HasTimeInLowRecords             pgtype.Bool
	HasTimeInTargetMinutes          pgtype.Bool
	HasTimeInTargetPercent          pgtype.Bool
	HasTimeInTargetRecords          pgtype.Bool
	HasTimeInVeryHighMinutes        pgtype.Bool
	HasTimeInVeryHighPercent        pgtype.Bool
	HasTimeInVeryHighRecords        pgtype.Bool
	HasTimeInVeryLowMinutes         pgtype.Bool
	HasTimeInVeryLowPercent         pgtype.Bool
	HasTimeInVeryLowRecords         pgtype.Bool
	HasTotalRecords                 pgtype.Bool
	HoursWithData                   pgtype.Int4
	HoursWithDataDelta              pgtype.Int4
	Max                             pgtype.Float8
	MaxDelta                        pgtype.Float8
	Min                             pgtype.Float8
	MinDelta                        pgtype.Float8
	StandardDeviation               pgtype.Float8
	StandardDeviationDelta          pgtype.Float8
	TimeCgmUseMinutes               pgtype.Int4
	TimeCgmUseMinutesDelta          pgtype.Int4
	TimeCgmUsePercent               pgtype.Float8
	TimeCgmUsePercentDelta          pgtype.Float8
	TimeCgmUseRecords               pgtype.Int4
	TimeCgmUseRecordsDelta          pgtype.Int4
	TimeInAnyHighMinutes            pgtype.Int4
	TimeInAnyHighMinutesDelta       pgtype.Int4
	TimeInAnyHighPercent            pgtype.Float8
	TimeInAnyHighPercentDelta       pgtype.Float8
	TimeInAnyHighRecords            pgtype.Int4
	TimeInAnyHighRecordsDelta       pgtype.Int4
	TimeInAnyLowMinutes             pgtype.Int4
	TimeInAnyLowMinutesDelta        pgtype.Int4
	TimeInAnyLowPercent             pgtype.Float8
	TimeInAnyLowPercentDelta        pgtype.Float8
	TimeInAnyLowRecords             pgtype.Int4
	TimeInAnyLowRecordsDelta        pgtype.Int4
	TimeInExtremeHighMinutes        pgtype.Int4
	TimeInExtremeHighMinutesDelta   pgtype.Int4
	TimeInExtremeHighPercent        pgtype.Float8
	TimeInExtremeHighPercentDelta   pgtype.Float8
	TimeInExtremeHighRecords        pgtype.Int4
	TimeInExtremeHighRecordsDelta   pgtype.Int4
	TimeInHighMinutes               pgtype.Int4
	TimeInHighMinutesDelta          pgtype.Int4
	TimeInHighPercent               pgtype.Float8
	TimeInHighPercentDelta          pgtype.Float8
	TimeInHighRecords               pgtype.Int4
	TimeInHighRecordsDelta          pgtype.Int4
	TimeInLowMinutes                pgtype.Int4
	TimeInLowMinutesDelta           pgtype.Int4
	TimeInLowPercent                pgtype.Float8
	TimeInLowPercentDelta           pgtype.Float8
	TimeInLowRecords                pgtype.Int4
	TimeInLowRecordsDelta           pgtype.Int4
	TimeInTargetMinutes             pgtype.Int4
	TimeInTargetMinutesDelta        pgtype.Int4
	TimeInTargetPercent             pgtype.Float8
	TimeInTargetPercentDelta        pgtype.Float8
	TimeInTargetRecords             pgtype.Int4
	TimeInTargetRecordsDelta        pgtype.Int4
	TimeInVeryHighMinutes           pgtype.Int4
	TimeInVeryHighMinutesDelta      pgtype.Int4
	TimeInVeryHighPercent           pgtype.Float8
	TimeInVeryHighPercentDelta      pgtype.Float8
	TimeInVeryHighRecords           pgtype.Int4
	TimeInVeryHighRecordsDelta      pgtype.Int4
	TimeInVeryLowMinutes            pgtype.Int4
	TimeInVeryLowMinutesDelta       pgtype.Int4
	TimeInVeryLowPercent            pgtype.Float8
	TimeInVeryLowPercentDelta       pgtype.Float8
	TimeInVeryLowRecords            pgtype.Int4
	TimeInVeryLowRecordsDelta       pgtype.Int4
	TotalRecords                    pgtype.Int4
	TotalRecordsDelta               pgtype.Int4
}

func (q *Queries) InsertPatientSummaryPeriod(ctx context.Context, arg []InsertPatientSummaryPeriodParams) *InsertPatientSummaryPeriodBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.SummaryType,
			a.Period,
			a.AverageDailyRecords,
			a.AverageDailyRecordsDelta,
			a.AverageGlucoseMmol,
			a.AverageGlucoseMmolDelta,
			a.CoefficientOfVariation,
			a.CoefficientOfVariationDelta,
			a.DaysWithData,
			a.DaysWithDataDelta,
			a.GlucoseManagementIndicator,
			a.GlucoseManagementIndicatorDelta,
			a.HasAverageDailyRecords,
			a.HasAverageGlucoseMmol,
			a.HasGlucoseManagementIndicator,
			a.HasTimeCgmUseMinutes,
			a.HasTimeCgmUsePercent,
			a.HasTimeCgmUseRecords,
			a.HasTimeInAnyHighMinutes,
			a.HasTimeInAnyHighPercent,
			a.HasTimeInAnyHighRecords,
			a.HasTimeInAnyLowMinutes,
			a.HasTimeInAnyLowPercent,
			a.HasTimeInAnyLowRecords,
			a.HasTimeInExtremeHighMinutes,
			a.HasTimeInExtremeHighPercent,
			a.HasTimeInExtremeHighRecords,
			a.HasTimeInHighMinutes,
			a.HasTimeInHighPercent,
			a.HasTimeInHighRecords,
			a.HasTimeInLowMinutes,
			a.HasTimeInLowPercent,
			a.HasTimeInLowRecords,
			a.HasTimeInTargetMinutes,
			a.HasTimeInTargetPercent,
			a.HasTimeInTargetRecords,
			a.HasTimeInVeryHighMinutes,
			a.HasTimeInVeryHighPercent,
			a.HasTimeInVeryHighRecords,
			a.HasTimeInVeryLowMinutes,
			a.HasTimeInVeryLowPercent,
			a.HasTimeInVeryLowRecords,
			a.HasTotalRecords,
			a.HoursWithData,
			a.HoursWithDataDelta,
			a.Max,
			a.MaxDelta,
			a.Min,
			a.MinDelta,
			a.StandardDeviation,
			a.StandardDeviationDelta,
			a.TimeCgmUseMinutes,
			a.TimeCgmUseMinutesDelta,
			a.TimeCgmUsePercent,
			a.TimeCgmUsePercentDelta,
			a.TimeCgmUseRecords,
			a.TimeCgmUseRecordsDelta,
			a.TimeInAnyHighMinutes,
			a.TimeInAnyHighMinutesDelta,
			a.TimeInAnyHighPercent,
			a.TimeInAnyHighPercentDelta,
			a.TimeInAnyHighRecords,
			a.TimeInAnyHighRecordsDelta,
			a.TimeInAnyLowMinutes,
			a.TimeInAnyLowMinutesDelta,
			a.TimeInAnyLowPercent,
			a.TimeInAnyLowPercentDelta,
			a.TimeInAnyLowRecords,
			a.TimeInAnyLowRecordsDelta,
			a.TimeInExtremeHighMinutes,
			a.TimeInExtremeHighMinutesDelta,
			a.TimeInExtremeHighPercent,
			a.TimeInExtremeHighPercentDelta,
			a.TimeInExtremeHighRecords,
			a.TimeInExtremeHighRecordsDelta,
			a.TimeInHighMinutes,
			a.TimeInHighMinutesDelta,
			a.TimeInHighPercent,
			a.TimeInHighPercentDelta,
			a.TimeInHighRecords,
			a.TimeInHighRecordsDelta,
			a.TimeInLowMinutes,
			a.TimeInLowMinutesDelta,
			a.TimeInLowPercent,
			a.TimeInLowPercentDelta,
			a.TimeInLowRecords,
			a.TimeInLowRecordsDelta,
			a.TimeInTargetMinutes,
			a.TimeInTargetMinutesDelta,
			a.TimeInTargetPercent,
			a.TimeInTargetPercentDelta,
			a.TimeInTargetRecords,
			a.TimeInTargetRecordsDelta,
			a.TimeInVeryHighMinutes,
			a.TimeInVeryHighMinutesDelta,
			a.TimeInVeryHighPercent,
			a.TimeInVeryHighPercentDelta,
			a.TimeInVeryHighRecords,
			a.TimeInVeryHighRecordsDelta,
			a.TimeInVeryLowMinutes,
			a.TimeInVeryLowMinutesDelta,
			a.TimeInVeryLowPercent,
			a.TimeInVeryLowPercentDelta,
			a.TimeInVeryLowRecords,
			a.TimeInVeryLowRecordsDelta,
			a.TotalRecords,
			a.TotalRecordsDelta,
		}
		batch.Queue(insertPatientSummaryPeriod, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientSummaryPeriodBatchResults{br, len(arg), false}
}

func (b *InsertPatientSummaryPeriodBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientSummaryPeriodBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertPatientTag = `-- name: InsertPatientTag :batchexec
INSERT INTO patient_tags (patient_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertPatientTagBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertPatientTagParams struct {
	PatientID string
	TagID     string
}

func (q *Queries) InsertPatientTag(ctx context.Context, arg []InsertPatientTagParams) *InsertPatientTagBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PatientID,
			a.TagID,
		}
		batch.Queue(insertPatientTag, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertPatientTagBatchResults{br, len(arg), false}
}

func (b *InsertPatientTagBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertPatientTagBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
