// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	SessionTokenScopes = "sessionToken.Scopes"
)

// Clinic defines model for Clinic.
type Clinic struct {
	Address    *string             `json:"address,omitempty"`
	City       *string             `json:"city,omitempty"`
	ClinicSize *int                `json:"clinicSize,omitempty"`
	ClinicType *string             `json:"clinicType,omitempty"`
	Country    *string             `json:"country,omitempty"`
	Email      openapi_types.Email `json:"email"`

	// String representation of a resource id
	Id           Id             `json:"id"`
	Name         string         `json:"name"`
	PhoneNumbers *[]PhoneNumber `json:"phoneNumbers,omitempty"`
	PostalCode   *string        `json:"postalCode,omitempty"`
	State        *string        `json:"state,omitempty"`
}

// Clinician defines model for Clinician.
type Clinician struct {

	// The email of the clinician
	Email openapi_types.Email `json:"email"`

	// String representation of a resource id
	Id *Id `json:"id,omitempty"`

	// The id of the invite if it hasn't been accepted
	InviteId *string `json:"inviteId,omitempty"`

	// The name of the clinician
	Name        *string               `json:"name,omitempty"`
	Permissions *ClinicianPermissions `json:"permissions,omitempty"`

	// The user id of the clinician
	UserId *string `json:"userId,omitempty"`
}

// ClinicianPermissions defines model for ClinicianPermissions.
type ClinicianPermissions []string

// Clinicians defines model for Clinicians.
type Clinicians []Clinician

// Clinics defines model for Clinics.
type Clinics []Clinic

// Error defines model for Error.
type Error struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Id defines model for Id.
type Id string

// Patient defines model for Patient.
type Patient struct {

	// YYYY-MM-DD
	BirthDate *openapi_types.Date `json:"birthDate,omitempty"`

	// The email of the patient
	Email *openapi_types.Email `json:"email,omitempty"`

	// The full name of the patient
	FullName *string `json:"fullName,omitempty"`

	// String representation of a Tidepool User ID
	Id UserId `json:"id"`

	// The medical record number of the patient
	Mrn           *string             `json:"mrn,omitempty"`
	Permissions   *PatientPermissions `json:"permissions,omitempty"`
	TargetDevices *[]string           `json:"targetDevices,omitempty"`
}

// PatientPermissions defines model for PatientPermissions.
type PatientPermissions struct {

	// Allow custodial control of an account
	Custodian *map[string]interface{} `json:"custodian,omitempty"`

	// Allow annotating data
	Note *map[string]interface{} `json:"note,omitempty"`

	// Allow full control of account
	Root *map[string]interface{} `json:"root,omitempty"`

	// Allow uploading data
	Upload *map[string]interface{} `json:"upload,omitempty"`

	// Allow viewing data
	View *map[string]interface{} `json:"view,omitempty"`
}

// Patients defines model for Patients.
type Patients []Patient

// PhoneNumber defines model for PhoneNumber.
type PhoneNumber struct {
	Number string  `json:"number"`
	Type   *string `json:"type,omitempty"`
}

// UserId defines model for UserId.
type UserId string

// ListClinicsParams defines parameters for ListClinics.
type ListClinicsParams struct {
	Limit       *int    `json:"limit,omitempty"`
	Offset      *int    `json:"offset,omitempty"`
	Sort        *string `json:"sort,omitempty"`
	ClinicianId *string `json:"clinicianId,omitempty"`
	PatientId   *string `json:"patientId,omitempty"`
}

// CreateClinicJSONBody defines parameters for CreateClinic.
type CreateClinicJSONBody Clinic

// UpdateClinicJSONBody defines parameters for UpdateClinic.
type UpdateClinicJSONBody Clinic

// ListCliniciansParams defines parameters for ListClinicians.
type ListCliniciansParams struct {
	Search *string `json:"search,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

// CreateClinicianJSONBody defines parameters for CreateClinician.
type CreateClinicianJSONBody Clinician

// UpdateClinicianJSONBody defines parameters for UpdateClinician.
type UpdateClinicianJSONBody Clinician

// ListPatientsParams defines parameters for ListPatients.
type ListPatientsParams struct {

	// Full text search query that matches patient's name, email and mrn
	Search *string `json:"search,omitempty"`
	Offset *int    `json:"offset,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
}

// CreatePatientAccountJSONBody defines parameters for CreatePatientAccount.
type CreatePatientAccountJSONBody Patient

// UpdatePatientJSONBody defines parameters for UpdatePatient.
type UpdatePatientJSONBody Patient

// CreateClinicJSONRequestBody defines body for CreateClinic for application/json ContentType.
type CreateClinicJSONRequestBody CreateClinicJSONBody

// UpdateClinicJSONRequestBody defines body for UpdateClinic for application/json ContentType.
type UpdateClinicJSONRequestBody UpdateClinicJSONBody

// CreateClinicianJSONRequestBody defines body for CreateClinician for application/json ContentType.
type CreateClinicianJSONRequestBody CreateClinicianJSONBody

// UpdateClinicianJSONRequestBody defines body for UpdateClinician for application/json ContentType.
type UpdateClinicianJSONRequestBody UpdateClinicianJSONBody

// CreatePatientAccountJSONRequestBody defines body for CreatePatientAccount for application/json ContentType.
type CreatePatientAccountJSONRequestBody CreatePatientAccountJSONBody

// UpdatePatientJSONRequestBody defines body for UpdatePatient for application/json ContentType.
type UpdatePatientJSONRequestBody UpdatePatientJSONBody

