// Package Clinic provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bNhD+KwS3j4rtvgQo/C110sJb8wK3xTYEQcGY55idRCoklcTz/N8Hknq1KUt2",
	"7KLu+qGoIpE68u6e5x6ePMdjEcWCA9cK9+dYjacQEXs5CBlnY3NFwvBygvvXcxxLEYPUDOyIL4ya//Qs",
	"BtzHSkvG7/BiEWAJ9wmTQHH/2g66CbJB4vYrjDVeBHP8q4QJ7uNfusUKuqn57gU8puYXZi7ToZmc3QrS",
	"K0b4FciIKcUEtyuioMaSxZoJjvvYPTTP0ERIJCEk5omashjdgn4E4Mi9SSHCKcrfqnCwtNW4aodpiNx9",
	"ojVIY2zwYXgxHHw5OT0fXvyb/uH+G57kN65GZx8Ho+HbsxEOlv2W3yBSkhkOcMLZfQJDZ0rLBIxrq75Y",
	"8sCqm9NxqrS1NQEd21FDX1SD9CEjfNgi6uXBG0ffuzeTCNXwjjaKZ9VxZYcUXroimmVI2MpHzH87du+t",
	"c9xm3kkXud43mRuyHaGys1a9kW98EeAzKYW0uV3dt6BQWj7jGu5AmgkRKEXuoEVSmFeU8OwseZK2gP8K",
	"pi/tIORu3jJ+hwhyIVnBLKFUglL+ZGZ65n8gEq6l/1kEmlCiyapzsrvNscWcRNZVEeMfgN/pKe6/8HBB",
	"PBUcLpLoFuQS41QMczvCu1p3o9WaKsRjjAulSTioRrx4s9JE1706DW0RwWVzAX46gicSxaHbQXpdCRh+",
	"1ev10DlhHFHJHgA7ZOHj16+PcYBDMSZpOvxBQp5oNJAAf+NKhHJX49/ElKPzhJlUW3Zr5j98fHx8lP47",
	"LtYcEcbxYmF25oFdTcEpKo5zQQbCZQy2qzDrq0TZ554VrsTajGd8Iuyb03k5fB5AKreRF52eMSVi4CRm",
	"JiCdXqeHLZNN7bK6bpa9vgO96osRaMngAVDIlEZikqJUdRAaOU5QiNCIcUTiGJFET4Vk/7i4WsvSXhvO",
	"xO9Bp0RllyBJBNoG8HqOmTF2n4A0JTONuJhMFJhUc5zpoy3Dsr6pIYvYdjOVkPpSUpC+2QVE/JPL9XKL",
	"6UWBWTf5xtCxigVXLuVe9nqO2bkGbkNI4jhkDlzdr8rEcV56X56TzcXbk6iL5Rp1+bsZ9XrDRayz7QqK",
	"x9RbQm3WgdLO5qv923wn5C2jFLixePwtdjnkRouSEH0E+QASZQMDrGCcSFvyrm8CrJIoIqbGVYH1dCSF",
	"JeVr/Gl4enZ1efnByVkcVNRt8Weub/FNWjVWeeCEUkQQh8eiTFfBfSVUPbqr7/qsQDJqqRU4jQXjBqoW",
	"EFMgDnopIv48yvZw9Pnj2Wh42owMmx5vBZ3tLFKlY8zCiaFnoG+ZXt2r0ESKyGggEoZIC2SCkHq67KPW",
	"GrZcT/LAZMY89SSorPopCquL9pSfNSTQBrTNIHsuKE4ozbVLgYkbMyWret2cr1V3nl8zunD2Q3D6qLqS",
	"U3tfoXx8GrswzGrjCjbclJUjy6CwiP1Z9d04uZ5UDGV4lcN70Kp0dmv2UsFim7hoH2Vv6Vi5UQX8xsmf",
	"p/tfIpHo/dmnMl2sj5pPgRlh6JEzqfezM6CWCazl4TLGUlGjuvP0qhW+UDp4Q3BlJ+CrzNQPCKxMkitk",
	"jgAysq5AgmcuM/cR4TOj1vUUWuCtrdf2grVy0+J/i7S44vmtcJYVsFboGvhFnK9QffcQqhMA5c1soovX",
	"VbQ6x63UrmdDqM3h7CB0WO6aXZxN2pasDXFkOyLj6ep2zwVlk1ld1K/MJF/c93sGea5Yr2wKFf3Dg0S5",
	"28w2KPeTZ+lM0NwUI0ttMSd0hSx3s5uIovq56qC7Yjc/JfoWvGj28E6K6BBYck1vqDgPa9GiSeRN/30w",
	"pydfdt3FGVJDARwewxkaSyAaaOGOlFAq361XWjmsoYlTrN640DaID7onwwj/JPZC2u0bOSOIhOFwpcSY",
	"uUPUI9PTrO1GeCmI7ZTyQbZ22shnRvh2DLVWS5c5I/+s2L5c7rA3tDF/HFh9+X6LSrDbxlOtkE9iSnTW",
	"Cynl3RIrN+v7+vzbV+la/gVNbfU6KK2+VW7W8n9c+slPLd9kWj3vk2XUD7TM/C1IKO9Z/VTsP16jr55P",
	"sx28E/KgxXrWW99IqJdyfo8yvUiS/Yv0zA87UejZz3YOXJ6n29hGnHsTvIGv234Uop6PQuPmHvZy7h7M",
	"Z6H1ojzdxk6bBmtUehuv19fInX1U2pA9DqqkHEL/J9jll6umjnu7rPMJdH/e7b5g+X7A/WNI83Rnz+d+",
	"a88swCViIkPcx1Ot4363G4oxCadC6f6b3pue/bl88Vz1u10KDy86FB46mlGIhQg7Qt55xt0TOwxCEUfA",
	"dfPwl5sMhyfnyY4V3C71muaQmK0bUr+3m8V/AQAA//+wTySMyTMAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

